/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _10 = "._1wyb7vkz{font-size:1pc}";
const _9 = "._syaz5scu{color:red}";
const _8 = "._19bvftgi{padding-left:8px}";
const _7 = "._n3tdftgi{padding-bottom:8px}";
const _6 = "._u5f3ftgi{padding-right:8px}";
const _5 = "._ca0qftgi{padding-top:8px}";
const _4 = "._18u0idpf{margin-left:0}";
const _3 = "._otyridpf{margin-bottom:0}";
const _2 = "._2hwxidpf{margin-right:0}";
const _ = "._19pkidpf{margin-top:0}";
const StaticDiv = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _10]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_19pkidpf _2hwxidpf _otyridpf _18u0idpf _ca0qftgi _u5f3ftgi _n3tdftgi _19bvftgi _syaz5scu _1wyb7vkz", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  StaticDiv.displayName = 'StaticDiv';
}