/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _5 = "._1t2qazsu label{color:var(--ds-text-subtle,#505258)}";
const _4 = "._1rgf12x7 input{margin-left:var(--ds-space-075,6px)}";
const _3 = "._x5bdze3t input{margin-bottom:var(--ds-space-0,0)}";
const _2 = "._12hv12x7 input{margin-right:var(--ds-space-075,6px)}";
const _ = "._2x4gze3t input{margin-top:var(--ds-space-0,0)}";
const Wrapper = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2, _3, _4, _5]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_2x4gze3t _12hv12x7 _x5bdze3t _1rgf12x7 _1t2qazsu", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Wrapper.displayName = 'Wrapper';
}
export const Component = () => <Wrapper>
		<label>
			<input type="checkbox" />
		</label>
	</Wrapper>;