/* input.tsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import React from 'react';
const _2 = "._ect4ttxp{font-family:var(--ds-font-family-body,\"Atlassian Sans\",ui-sans-serif,-apple-system,BlinkMacSystemFont,\"Segoe UI\",Ubuntu,\"Helvetica Neue\",sans-serif)}";
const _ = "._1bsb1osq{width:100%}";
export const Gadget = () => {
  const fullWidthStyles = null;
  return <CC>
  <CS>{[_, _2]}</CS>
  {<div className={ax(["_1bsb1osq", "_ect4ttxp"])} />}
  </CC>;
};
const fontStyles = null;