/* input.tsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import React from 'react';
import { Pressable, Text } from '@atlaskit/primitives/compiled';
const _13 = "._jf4cnqa1:hover{text-decoration-style:solid}";
const _12 = "._1bnxglyw:hover{text-decoration-line:none}";
const _11 = "._9oik1r31:hover{text-decoration-color:currentColor}";
const _10 = "._19bvze3t{padding-left:var(--ds-space-0,0)}";
const _9 = "._n3tdze3t{padding-bottom:var(--ds-space-0,0)}";
const _8 = "._u5f3ze3t{padding-right:var(--ds-space-0,0)}";
const _7 = "._ca0qze3t{padding-top:var(--ds-space-0,0)}";
const _6 = "._1bsb1ns9{width:-moz-fit-content;width:fit-content}";
const _5 = "._bfhk1j28{background-color:transparent}";
const _4 = "._2rko12b0{border-radius:var(--ds-radius-small,4px)}";
const _3 = "._ajmmnqa1{text-decoration-style:solid}";
const _2 = "._1hms8stv{text-decoration-line:underline}";
const _ = "._4bfu1r31{text-decoration-color:currentColor}";
const styles = {
  trigger: "_4bfu1r31 _1hms8stv _ajmmnqa1 _2rko12b0 _bfhk1j28 _1bsb1ns9 _ca0qze3t _u5f3ze3t _n3tdze3t _19bvze3t _9oik1r31 _1bnxglyw _jf4cnqa1"
};
export const Example = () => <CC>
  <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13]}</CS>
  {<Pressable xcss={styles.trigger}>
		<Text size="large" weight="bold" color="color.text">
			Trigger content
		</Text>
	</Pressable>}
</CC>;