/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { LAYOUT_OFFSET } from './layout-offset';
const _ = "._4t3i1i8v{height:calc(100vh - var(--topNavigationHeight, 0px) - var(--bannerHeight, 0px))}";
const Container = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_4t3i1i8v", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Container.displayName = 'Container';
}
export const Component = () => <Container>Content</Container>;