/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import * as React from 'react';
const _5 = "._1bah1yb4{justify-content:space-between}";
const _4 = "._4cvr1h6o{align-items:center}";
const _3 = "._2lx21bp4{flex-direction:column}";
const _2 = "._1e0c1txw{display:flex}";
const _ = "._zulp7vkz{gap:1pc}";
const FlexContainer = () => <CC>
  <CS>{[_, _2, _3, _4, _5]}</CS>
  {<div className={ax(["_zulp7vkz _1e0c1txw _2lx21bp4 _4cvr1h6o _1bah1yb4"])}>
    Content
  </div>}
</CC>;