/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const styles = {
  root: "_1q511wn3 _85i51wn3"
};
export const Component = () => <div className={styles.root}>Hi</div>;