/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const styles = {
  primary: "_ca0qftgi _u5f37vkz _n3tdftgi _19bv7vkz _2rko1y44 _syaz13q2 _bfhku67f",
  secondary: "_ca0qftgi _u5f37vkz _n3tdftgi _19bv7vkz _2rko1y44 _syaz17nt _bfhkis24"
};