/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "._14rn5scu:after{color:red}";
const _ = "._aetrjphk:after{content:\"*\"}";
const Asterisk = forwardRef(({
  as: C = "span",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_aetrjphk _14rn5scu", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Asterisk.displayName = 'Asterisk';
}