/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import * as React from 'react';
const _2 = "._1p1dangw{text-transform:uppercase}";
const _ = "._k48p8n31{font-weight:bold}";
const MyComponent = () => <CC>
  <CS>{[_, _2]}</CS>
  {<span className={ax(["_k48p8n31 _1p1dangw"])}>
    Hello
  </span>}
</CC>;