/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _10 = "@media (min-width:48rem){._1lp7vrvc{flex-direction:row}}";
const _9 = "@media (min-width:0rem){._1alv1bp4{flex-direction:column}}";
const _8 = "._1tjq4viv span{color:var(--ds-text,#292a2e)!important}";
const _7 = "._19bvu2gc{padding-left:var(--ds-space-100,8px)}";
const _6 = "._19pkxy5q{margin-top:var(--ds-space-400,2pc)}";
const _5 = "._1e0c1txw{display:flex}";
const _4 = "._4cvr1h6o{align-items:center}";
const _3 = "._zulpu2gc{gap:var(--ds-space-100,8px)}";
const _2 = "._2rko12b0{border-radius:var(--ds-radius-small,4px)}";
const _ = "._11q7vuon{background:var(--ds-surface,#fff)}";
const media = {
  above: {
    xxs: '@media (min-width: 0rem)',
    sm: '@media (min-width: 48rem)'
  }
};
const styles = null;
export const Component = () => <CC>
  <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _10]}</CS>
  {<div className={ax(["_11q7vuon _2rko12b0 _zulpu2gc _4cvr1h6o _1e0c1txw _19pkxy5q _19bvu2gc _1tjq4viv _1alv1bp4 _1lp7vrvc"])}>
    <span>Hi</span>
  </div>}
</CC>;