/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import React from 'react';
const _10 = "._bfhk1i1c{background-color:cyan}";
const _9 = "._bfhk1paw{background-color:lime}";
const _8 = "._10jz105o #target-id:hover{opacity:.5}";
const _7 = "._12nkftgi #target-id{margin-top:8px}";
const _6 = "._10r21a6z .helper-class{color:tomato}";
const _5 = "._mn4j1y44 .helper-class{padding-left:4px}";
const _4 = "._38gu1y44 .helper-class{padding-bottom:4px}";
const _3 = "._tozs1y44 .helper-class{padding-right:4px}";
const _2 = "._1ud41y44 .helper-class{padding-top:4px}";
const _ = "._syaz15td{color:#639}";
const selectors = {
  helper: 'helper-class',
  id: 'target-id'
};
const Component = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    isActive,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _10]}</CS>
        <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax(["_syaz15td _1ud41y44 _tozs1y44 _38gu1y44 _mn4j1y44 _10r21a6z _12nkftgi _10jz105o", __cmplp.isActive ? "_bfhk1paw" : "_bfhk1i1c", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Component.displayName = 'Component';
}
export const Styled = () => <Component isActive>
    <span className="helper-class">Helper</span>
    <span id="target-id">Target</span>
  </Component>;