/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const styles = {
  danger: "_syaz5scu _k48p8n31",
  success: "_syazbf54 _k48p8n31"
};