/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _9 = "._g51qdabe:not(:has([data-component-selector=jira-issue-field-original-estimate-read-view-container],[data-component-selector=jira-issue-field-inline-edit-read-view-container])){margin-right:calc(var(--ds-space-600, 3pc) + var(--ds-space-100, 8px))}";
const _8 = "._lcxvglyw{pointer-events:none}";
const _7 = "._1dbovuon:not(:has([data-component-selector=jira-issue-field-original-estimate-read-view-container],[data-component-selector=jira-issue-field-inline-edit-read-view-container])){z-index:var(--ds-surface,#fff)}";
const _6 = "._1nf9idpf [data-component-selector=jira-issue-field-inline-edit-read-view-container]{margin-right:0}";
const _5 = "._wv4j6up6 [data-component-selector=jira-issue-field-inline-edit-read-view-container]{margin-top:calc(var(--ds-space-negative-100, -8px)*.125)}";
const _4 = "._1bb7idpf [data-component-selector=jira-issue-field-inline-edit-read-view-container]{margin-bottom:0}";
const _3 = "._1bt61i6y [data-component-selector=jira-issue-field-inline-edit-read-view-container]{margin-left:var(--ds-space-negative-025,-2px)}";
const _2 = "._gx371q9c [data-component-selector=jira-issue-field-inline-edit-read-view-container]{white-space:nowrap}";
const _ = "._4t3ipxbi{height:var(--ds-space-200,1pc)}";
const READ_VIEW_CONTAINER_SELECTOR = '[data-component-selector=jira-issue-field-inline-edit-read-view-container]';
const ORIGINAL_READ_VIEW_SELECTOR = '[data-component-selector=jira-issue-field-original-estimate-read-view-container]';
const Wrapper = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    disableClick,
    isIncrementPlanningBoard,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9]}</CS>
        <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax(["_4t3ipxbi _gx371q9c _1bt61i6y _1bb7idpf _wv4j6up6 _1nf9idpf _1dbovuon", __cmplp.disableClick && "_lcxvglyw", __cmplp.isIncrementPlanningBoard && "_g51qdabe", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Wrapper.displayName = 'Wrapper';
}
export const Component = ({
  disableClick,
  isIncrementPlanningBoard
}) => <Wrapper disableClick={disableClick} isIncrementPlanningBoard={isIncrementPlanningBoard} />;