/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _7 = "._syaz1cj8{color:var(--_xexnhp)}";
const _6 = "._19bv19bv{padding-left:10px}";
const _5 = "._n3td19bv{padding-bottom:10px}";
const _4 = "._u5f319bv{padding-right:10px}";
const _3 = "._ca0q19bv{padding-top:10px}";
const _2 = "._1wybdlk8{font-size:14px}";
const _ = "._syaz13q2{color:blue}";
const StyledDiv = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_syaz13q2 _1wybdlk8", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  StyledDiv.displayName = 'StyledDiv';
}
const StyledWithProps = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_3, _4, _5, _6, _7]}</CS>
        <C {...__cmplp} style={{
      ...__cmpls,
      "--_xexnhp": ix(__cmplp.color)
    }} ref={__cmplr} className={ax(["_ca0q19bv _u5f319bv _n3td19bv _19bv19bv _syaz1cj8", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  StyledWithProps.displayName = 'StyledWithProps';
}