/* input.tsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import React from 'react';
const _2 = "._1g921a76{styled-category-item:var(--_1mso4je)}";
const _ = "._1g922sth{styled-category-item:var(--_120drhm)}";
const ICON_CONTAINER_SELECTOR = 'styled-category-item';
type Props = {
  error: boolean;
};
const Wrapper = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    error,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_, _2]}</CS>
        <C {...__cmpldp} style={{
      ...__cmpls,
      "--_120drhm": ix({}),
      "--_1mso4je": ix({
        display: 'none'
      })
    }} ref={__cmplr} className={ax(["", __cmplp.error ? "_1g922sth" : "_1g921a76", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Wrapper.displayName = 'Wrapper';
}
export const Example = (props: Props) => <Wrapper {...props}>content</Wrapper>;