/* input.tsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _ = "._18u01iwj{margin-left:var(--_1v54z33)}";
// Mirrors the Jira action-button Counter style that returns an arrow function
// which then returns a conditional string.
const Counter = forwardRef(({
  as: C = "span",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    hasWatchers,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_]}</CS>
        <C {...__cmpldp} style={{
      ...__cmpls,
      "--_1v54z33": ix(() => __cmplp.hasWatchers ? 'var(--ds-space-025)' : 'var(--ds-space-0)')
    }} ref={__cmplr} className={ax(["_18u01iwj", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Counter.displayName = 'Counter';
}
export default function Component({
  hasWatchers
}: {
  hasWatchers?: boolean;
}) {
  return <Counter hasWatchers={hasWatchers}>count</Counter>;
}