/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _ = "._t9ec14w8{transform:rotate(90deg)}";
export const styles = null;
const test = <CC>
  <CS>{[_]}</CS>
  {<div className={ax(["_t9ec14w8"])} />}
</CC>;