/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _6 = "._swr6stnw[aria-expanded=true]:after{position:absolute}";
const _5 = "._15opstnw[aria-current=page]:after{position:absolute}";
const _4 = "._ia7kb3bt[aria-expanded=true]:after{content:\"\"}";
const _3 = "._1ccmb3bt[aria-current=page]:after{content:\"\"}";
const _2 = "._1q6e1txw[aria-expanded=true]{display:flex}";
const _ = "._ty5w1txw[aria-current=page]{display:flex}";
const themedUnderline = {
  '&::after': {
    content: "''",
    position: 'absolute'
  }
};
const styles = null;
export const Component = () => <CC>
  <CS>{[_, _2, _3, _4, _5, _6]}</CS>
  {<div className={ax(["_ty5w1txw _1q6e1txw _1ccmb3bt _ia7kb3bt _15opstnw _swr6stnw"])} />}
</CC>;