/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const responsiveStyles = {
  mobile: "_ca0qftgi _u5f3ftgi _n3tdftgi _19bvftgi _1wybdlk8",
  desktop: "_ca0q7vkz _u5f37vkz _n3td7vkz _19bv7vkz _1wybf6fq"
};