/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _ = "._syaz13q2{color:blue}";
const MyComponent = ({
  customStyle
}) => <CC>
  <CS>{[_]}</CS>
  {<div style={customStyle} className={ax(["_syaz13q2"])}>Hello</div>}
</CC>;