/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "._zg8l1m30{font-style:italic}";
const _ = "._syaz1cnh{color:purple}";
const StyledSpan = forwardRef(({
  as: C = "span",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_syaz1cnh _zg8l1m30", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  StyledSpan.displayName = 'StyledSpan';
}