/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _ = "._syazke6v{color:var(--_s9qdny)}";
const MyComponent = ({
  isPrimary
}) => <CC>
  <CS>{[_]}</CS>
  {<div className={ax(["_syazke6v"])} style={{
    "--_s9qdny": ix(isPrimary ? 'blue' : 'red')
  }}>Hello</div>}
</CC>;