/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import * as React from 'react';
const _5 = "._14hh1l2s>span{text-overflow:ellipsis}";
const _4 = "._d38j15vq>span{overflow-y:hidden}";
const _3 = "._18j015vq>span{overflow-x:hidden}";
const _2 = "._ks4fpzub>span{max-width:calc(100% - 38px)}";
const _ = "._1e0c1txw{display:flex}";
const Copyable = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2, _3, _4, _5]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_1e0c1txw _ks4fpzub _18j015vq _d38j15vq _14hh1l2s", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Copyable.displayName = 'Copyable';
}
export const Component = () => <Copyable>
    <span>details</span>
  </Copyable>;