/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const learnMoreLink = 'https://www.atlassian.com/software/compass';
export const Component = () => <div>{learnMoreLink}</div>;