/* input.tsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import React from 'react';
import { fg } from '@atlassian/jira-feature-gating';
const _ = "._1tkea4yp{min-height:var(--_cvuqri)}";
const Comp = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    isFlexible,
    isSwimlaneMode,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_]}</CS>
        <C {...__cmpldp} style={{
      ...__cmpls,
      "--_cvuqri": ix(__cmplp.isFlexible && !__cmplp.isSwimlaneMode ? fg('flag') && 'calc(var(--board-scroll-element-height) * 1px - 8px)' : undefined)
    }} ref={__cmplr} className={ax(["_1tkea4yp", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Comp.displayName = 'Comp';
}
export const Component = () => <Comp isFlexible isSwimlaneMode={false} />;