/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const styles = {
  default: "_syazr3uz _30l313q2",
  active: "_syaz13q2 _30l31xek"
};