/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _8 = "._7ehiglyw:focus{box-shadow:none}";
const _7 = "._n1v1glyw :focus{box-shadow:none}";
const _6 = "._1hvw1o36:focus{outline-width:medium}";
const _5 = "._dg4t1o36 :focus{outline-width:medium}";
const _4 = "._49pcglyw:focus{outline-style:none}";
const _3 = "._14gfglyw :focus{outline-style:none}";
const _2 = "._nt751r31:focus{outline-color:currentColor}";
const _ = "._9qso1r31 :focus{outline-color:currentColor}";
const styles = {
  root: "_9qso1r31 _nt751r31 _14gfglyw _49pcglyw _dg4t1o36 _1hvw1o36 _n1v1glyw _7ehiglyw"
};
export function Component() {
  return <CC>
  <CS>{[_, _2, _3, _4, _5, _6, _7, _8]}</CS>
  {<div className={ax([styles.root])}>
      <button type="button">Child</button>
    </div>}
  </CC>;
}