/* input.tsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _5 = "._154iidpf{top:0}";
const _4 = "._154i1uac{top:var(--_1gg2u2w)}";
const _3 = "._1ltvidpf{left:0}";
const _2 = "._1ltv1ogh{left:var(--_1qibnji)}";
const _ = "._kqswh2mm{position:relative}";
type Position = {
  left?: number;
  top?: number;
};

// This mirrors the Jira toggle-buttons-old usage that triggered the crash: a styled
// component with dynamic properties that dereference optional chaining inside the
// arrow expression.
const Fieldset = forwardRef(({
  as: C = "fieldset",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    position,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_, _2, _3, _4, _5]}</CS>
        <C {...__cmpldp} style={{
      ...__cmpls,
      "--_1qibnji": ix(__cmplp.position?.left, "px"),
      "--_1gg2u2w": ix(__cmplp.position?.top, "px")
    }} ref={__cmplr} className={ax(["_kqswh2mm", __cmplp.position?.left ? "_1ltv1ogh" : "_1ltvidpf", __cmplp.position?.top ? "_154i1uac" : "_154iidpf", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Fieldset.displayName = 'Fieldset';
}
export default function Component(props: {
  position?: Position;
}) {
  return <Fieldset position={props.position}>hello</Fieldset>;
}