/* input.tsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _16 = "._17pe1wou td.tt_graph_percentage{width:3em}";
const _15 = "._4awn1l7b td.tt_graph_percentage{padding-right:3px}";
const _14 = "._16lkusic td.tt_graph_percentage{text-align:right}";
const _13 = "._1o2g1wug td.tt_graph_percentage{min-width:auto}";
const _12 = "._v4pn1ule img{display:block}";
const _11 = "._18iyidpf td{padding-block:0}";
const _10 = "._13dh1osq img.hideOnPrint{width:100%}";
const _9 = "._1n631y44 img.hideOnPrint{height:4px}";
const _8 = "._1s6didpf img.hideOnPrint{border:0}";
const _7 = "._1xdnt94y td.tt_spacer{min-width:1px}";
const _6 = "._1h15idpf td.tt_spacer{padding-left:0}";
const _5 = "._wsabidpf td.tt_spacer{padding-bottom:0}";
const _4 = "._ipzridpf td.tt_spacer{padding-right:0}";
const _3 = "._1j4widpf td.tt_spacer{padding-top:0}";
const _2 = "._1d34idpf tbody{border:0}";
const _ = "._1bsbys9h{width:5pc}";
type Props = {
  enabled: boolean;
};
export const Component = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    enabled,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16]}</CS>
        <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax(["", __cmplp.enabled ? "_1bsbys9h _1d34idpf _1j4widpf _ipzridpf _wsabidpf _1h15idpf _1xdnt94y _1s6didpf _1n631y44 _13dh1osq _18iyidpf _v4pn1ule _1o2g1wug _16lkusic _4awn1l7b _17pe1wou" : "_1d34idpf _1j4widpf _ipzridpf _wsabidpf _1h15idpf _18iyidpf _v4pn1ule _1o2g1wug", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Component.displayName = 'Component';
}
export const Example = () => <Component enabled />;