/* in.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix } from "@compiled/react/runtime";
import * as React from "react";

import { DARK_MODE, MEDIA_QUERY } from "./media";
export const responsiveStyles = null;
export const responsiveTemplate = null;
export const MediaExample = () => (
	<section
		className={ax(["_syaz11x8 _1pnl1gc2 _17lw8n31 _hjr51x77", "_syaz1lra _1pnl1he7 _hjr52e8d"])}
	>
		responsive media queries
	</section>
);
