/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { DARK_MODE, MEDIA_QUERY } from './media';
const _6 = "@media (min-width:900px){._1pnl15td{color:#639}}";
const _5 = "@media (prefers-color-scheme:dark){._hjr5qgb6{color:#e6e6fa}}";
const _4 = "._syaz1usb{color:#191970}";
const _3 = "@media (min-width:900px){._1pnlcc57{color:#4169e1}._17lw8n31{font-weight:bold}}";
const _2 = "@media (prefers-color-scheme:dark){._hjr5u67f{color:#fff}}";
const _ = "._syazr3uz{color:#000}";
export const responsiveStyles = null;
export const responsiveTemplate = null;
export const MediaExample = () => <CC>
  <CS>{[_, _2, _3, _4, _5, _6]}</CS>
  {<section className={ax(["_syazr3uz _hjr5u67f _1pnlcc57 _17lw8n31", "_syaz1usb _hjr5qgb6 _1pnl15td"])}>
    responsive media queries
  </section>}
</CC>;