/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _ = "._o5724jg8{white-space:normal}";
const styles = {
  row: "_o5724jg8"
};
const Table = props => <div {...props} />;
export const Component = () => <CC>
  <CS>{[_]}</CS>
  {<Table rowCellXcss={styles.row} />}
</CC>;