/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import React from 'react';
const _17 = "._10fpdmq1{justify-self:var(--_pxmdp9)}";
const _16 = "._1bsbcbx4{width:var(--_1j3ddle)}";
const _15 = "._p12f1d9w{max-width:var(--_1lxvhyt)}";
const _14 = "._1bah1yb4{justify-content:space-between}";
const _13 = "._1e0c1txw{display:flex}";
const _12 = "@supports (position:sticky) or (position:-webkit-sticky){._s9qlu2gc{padding-left:var(--ds-space-100,8px)}}";
const _11 = "@supports (position:sticky) or (position:-webkit-sticky){._s9ql1ejb{padding-left:var(--ds-space-300,24px)}}";
const _10 = "@supports (position:sticky) or (position:-webkit-sticky){._s9qln7od{padding-left:unset}}";
const _9 = "@supports (position:sticky) or (position:-webkit-sticky){._4eq41ejb{padding-right:var(--ds-space-300,24px)}}";
const _8 = "@supports (position:sticky) or (position:-webkit-sticky){._1u8bu2gc{padding-bottom:var(--ds-space-100,8px)}}";
const _7 = "@supports (position:sticky) or (position:-webkit-sticky){._igsxz4f7{box-shadow:0 var(--ds-space-025,2px) var(--ds-border,#0b120e24)}}";
const _6 = "@supports (position:sticky) or (position:-webkit-sticky){._r372vuon{background:var(--ds-surface,#fff)}}";
const _5 = "@supports (position:sticky) or (position:-webkit-sticky){._r3721bhr{background:var(--ds-surface-overlay,#fff)}}";
const _4 = "@supports (position:sticky) or (position:-webkit-sticky){._vggs17df{padding-top:var(--_hn6azs)}}";
const _3 = "@supports (position:sticky) or (position:-webkit-sticky){}";
const _2 = "@supports (position:sticky) or (position:-webkit-sticky){._1ae31fcb{z-index:var(--_w6mvmh)}._nn8px0bf{margin-left:var(--ds-space-negative-100,-8px)}._uto9d5jx{top:var(--_1dtg6dp)}}";
const _ = "@supports (position:sticky) or (position:-webkit-sticky){._1axi1if8{position:sticky}}";
const extraTopOffset = -1;
const StickyWrapper = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    isEmbedMode,
    zIndex,
    topOffset,
    showKeyline,
    applyVisualRefreshChanges,
    showPaddingTopOnlyOnKeyline,
    isTabLayout,
    isSidebarPanelOpened,
    flexStyle,
    isWideLayout,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, _17]}</CS>
        <C {...__cmpldp} style={{
      ...__cmpls,
      "--_w6mvmh": ix(__cmplp.zIndex),
      "--_1dtg6dp": ix(`${__cmplp.topOffset + extraTopOffset}px`),
      "--_hn6azs": ix((() => {
        if (__cmplp.showPaddingTopOnlyOnKeyline) {
          return __cmplp.showKeyline && __cmplp.applyVisualRefreshChanges ? "var(--ds-space-100, 8px)" : `${-extraTopOffset}px`;
        }
        return __cmplp.applyVisualRefreshChanges ? "var(--ds-space-100, 8px)" : `${-extraTopOffset}px`;
      })()),
      "--_1lxvhyt": ix(__cmplp.isWideLayout ? '1920px' : 'inherit'),
      "--_1j3ddle": ix(__cmplp.isWideLayout ? '100%' : 'inherit'),
      "--_pxmdp9": ix(__cmplp.isWideLayout ? 'center' : 'inherit')
    }} ref={__cmplr} className={ax(["_1axi1if8 _1ae31fcb _nn8px0bf _uto9d5jx _vggs17df", __cmplp.isEmbedMode ? "_r3721bhr" : "_r372vuon", __cmplp.showKeyline ? "_igsxz4f7" : undefined, __cmplp.showKeyline && __cmplp.applyVisualRefreshChanges ? "_1u8bu2gc" : undefined, __cmplp.isTabLayout ? "_4eq41ejb" : undefined, __cmplp.isSidebarPanelOpened ? "_s9qln7od" : __cmplp.isTabLayout ? "_s9ql1ejb" : "_s9qlu2gc", __cmplp.flexStyle && "_1e0c1txw _1bah1yb4 _p12f1d9w _1bsbcbx4 _10fpdmq1", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  StickyWrapper.displayName = 'StickyWrapper';
}
const Fixture = () => <StickyWrapper topOffset={0} showKeyline isEmbedMode zIndex={10} applyVisualRefreshChanges flexStyle isWideLayout isTabLayout showPaddingTopOnlyOnKeyline isSidebarPanelOpened={false}>
    content
  </StickyWrapper>;
export default Fixture;