/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import * as React from 'react';
const _6 = "._gf5zidpf>ul>li{padding-left:0}";
const _5 = "._1ude1y44>ul>li{padding-bottom:4px}";
const _4 = "._qm8yidpf>ul>li{padding-right:0}";
const _3 = "._17aa1y44>ul>li{padding-top:4px}";
const _2 = "._1skyglyw>ul{list-style:none}";
const _ = "._syaz13q2{color:blue}";
const MyComponent = () => <CC>
  <CS>{[_, _2, _3, _4, _5, _6]}</CS>
  {<div className={ax(["_syaz13q2 _1skyglyw _17aa1y44 _qm8yidpf _1ude1y44 _gf5zidpf"])}>
    Content
  </div>}
</CC>;