/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import React from 'react';
const _ = "._16jlfmrs{flex-grow:0.050}";
const styles = {
  root: "_16jlfmrs"
};
export const Component = () => <CC>
  <CS>{[_]}</CS>
  {<div className={ax([styles.root])} />}
</CC>;