/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "._syaz13q2{color:blue}";
const _ = "._syaz5scu{color:red}";
const First = () => <CC>
  <CS>{[_]}</CS>
  {<div className={ax(["_syaz5scu"])}>Red</div>}
</CC>;
const Second = () => <CC>
  <CS>{[_2]}</CS>
  {<div className={ax(["_syaz13q2"])}>Blue</div>}
</CC>;