/* input.tsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import React, { useCallback, useState } from 'react';
import { Box } from '@atlaskit/primitives/compiled';
const _9 = "._1reo15vq{overflow-x:hidden}";
const _8 = "._1e0c1txw{display:flex}";
const _7 = "._4cvr1h6o{align-items:center}";
const _6 = "._1bsb1osq{width:100%}";
const _5 = "._kqswh2mm{position:relative}";
const _4 = "._19bvu2gc{padding-left:var(--ds-space-100,8px)}";
const _3 = "._u5f3u2gc{padding-right:var(--ds-space-100,8px)}";
const _2 = "._4t3i1osq{height:100%}";
const _ = "._1r04ze3t{inset:var(--ds-space-0,0)}";
const styles = {
  cellWrapper: "_1r04ze3t _4t3i1osq _u5f3u2gc _19bvu2gc _kqswh2mm _1bsb1osq _4cvr1h6o _1e0c1txw _1reo15vq"
};
export default function Component({
  item
}: {
  item: any;
}) {
  const [hover, setHover] = useState(false);
  const onEnter = useCallback(() => setHover(true), []);
  const onLeave = useCallback(() => setHover(false), []);
  const onClick = useCallback(() => console.log(item?.key), [item?.key]);
  return <CC>
  <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9]}</CS>
  {<Box xcss={styles.cellWrapper} onMouseEnter={onEnter} onMouseLeave={onLeave}>
      <div onClick={onClick}>{hover ? 'Hover' : 'Idle'}</div>
    </Box>}
  </CC>;
}