/* input.tsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { sharedStyles } from './sharedStyles';
const _3 = "._1bsb1ogy{width:270px}";
const _2 = "._1bahesu3{justify-content:flex-end}";
const _ = "._1e0c1txw{display:flex}";
const ColumnPlaceholder = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2, _3]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_1e0c1txw _1bahesu3 _1bsb1ogy", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  ColumnPlaceholder.displayName = 'ColumnPlaceholder';
}
export const Component = () => <ColumnPlaceholder />;