/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { Box } from '@atlaskit/primitives/compiled';
const _ = "._1bsb1mjv{width:300px}";
const styles = {
  container: "_1bsb1mjv"
};
export const Component = () => <CC>
  <CS>{[_]}</CS>
  {<Box xcss={styles.container} />}
</CC>;