//! Byte-parity integration test: verifies the Rust `hash()` produces
//! identical strings to the upstream JS `hash()` for every test vector in
//! `tests/hash_vectors.json`.
//!
//! Vectors are generated by `scripts/hash-vectors.mjs` against the upstream
//! JS source. **DO NOT EDIT** the JSON file by hand — regenerate it via
//! the script so the JS-side oracle is preserved.

use compiled_utils::hash;

const VECTORS: &str = include_str!("hash_vectors.json");

#[test]
fn rust_hash_matches_js_hash_byte_for_byte() {
    // Tiny ad-hoc parser so we don't pull in serde_json just for tests.
    let parsed: Vec<(String, String)> = parse_vectors(VECTORS);
    assert!(!parsed.is_empty(), "no vectors loaded — regenerate hash_vectors.json");

    let mut failures: Vec<(String, String, String)> = Vec::new();
    for (input, expected) in &parsed {
        let actual = hash(input);
        if &actual != expected {
            failures.push((input.clone(), expected.clone(), actual));
        }
    }

    if !failures.is_empty() {
        let summary: String = failures.iter()
            .map(|(i, e, a)| format!("  hash({:?}) — JS={:?}  RS={:?}", i, e, a))
            .collect::<Vec<_>>()
            .join("\n");
        panic!("hash parity violations ({} of {}):\n{}", failures.len(), parsed.len(), summary);
    }
}

/// Parse the JSON vectors file. The file is `[ [input, hash], ... ]` —
/// every string is JSON-escaped. We hand-roll the parser to avoid a
/// serde_json test-dep.
fn parse_vectors(s: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    let bytes = s.as_bytes();
    let mut i = 0;
    // Skip the outer `[`.
    while i < bytes.len() && bytes[i] != b'[' { i += 1; }
    i += 1;
    loop {
        // Skip whitespace and any trailing comma.
        while i < bytes.len() && (bytes[i].is_ascii_whitespace() || bytes[i] == b',') { i += 1; }
        if i >= bytes.len() || bytes[i] == b']' { break; }
        // Expect an inner `[`.
        if bytes[i] != b'[' { break; }
        i += 1;
        let (input, ni) = parse_string(bytes, i);
        i = ni;
        // skip whitespace + comma.
        while i < bytes.len() && (bytes[i].is_ascii_whitespace() || bytes[i] == b',') { i += 1; }
        let (h, ni) = parse_string(bytes, i);
        i = ni;
        // skip to closing `]`.
        while i < bytes.len() && bytes[i] != b']' { i += 1; }
        i += 1;
        out.push((input, h));
    }
    out
}

fn parse_string(bytes: &[u8], mut i: usize) -> (String, usize) {
    while i < bytes.len() && bytes[i] != b'"' { i += 1; }
    i += 1; // past opening quote
    let mut buf = Vec::new();
    while i < bytes.len() {
        let b = bytes[i];
        if b == b'"' { i += 1; return (String::from_utf8(buf).unwrap(), i); }
        if b == b'\\' {
            i += 1;
            if i >= bytes.len() { break; }
            match bytes[i] {
                b'n' => buf.push(b'\n'),
                b't' => buf.push(b'\t'),
                b'r' => buf.push(b'\r'),
                b'"' => buf.push(b'"'),
                b'\\' => buf.push(b'\\'),
                b'/' => buf.push(b'/'),
                b'u' => {
                    // \uXXXX
                    let hex = std::str::from_utf8(&bytes[i + 1..i + 5]).unwrap_or("0000");
                    let code = u32::from_str_radix(hex, 16).unwrap_or(0);
                    if let Some(c) = char::from_u32(code) {
                        let mut tmp = [0u8; 4];
                        let s = c.encode_utf8(&mut tmp);
                        buf.extend_from_slice(s.as_bytes());
                    } else if (0xD800..=0xDBFF).contains(&code) {
                        // High surrogate — expect `\uXXXX` low surrogate next.
                        i += 5;
                        if i + 5 < bytes.len() && bytes[i] == b'\\' && bytes[i + 1] == b'u' {
                            let lo_hex = std::str::from_utf8(&bytes[i + 2..i + 6]).unwrap_or("0000");
                            let lo = u32::from_str_radix(lo_hex, 16).unwrap_or(0);
                            let cp = 0x10000 + ((code - 0xD800) << 10) + (lo - 0xDC00);
                            if let Some(c) = char::from_u32(cp) {
                                let mut tmp = [0u8; 4];
                                let s = c.encode_utf8(&mut tmp);
                                buf.extend_from_slice(s.as_bytes());
                            }
                            i += 5;
                            continue;
                        }
                    }
                    i += 4;
                }
                _ => buf.push(bytes[i]),
            }
            i += 1;
            continue;
        }
        buf.push(b);
        i += 1;
    }
    (String::from_utf8(buf).unwrap_or_default(), i)
}
