/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _9 = "._1a3lidpf [data-testid=header]{margin-left:0}";
const _8 = "._170zidpf [data-testid=header]{margin-bottom:0}";
const _7 = "._1fgoidpf [data-testid=header]{margin-right:0}";
const _6 = "._i6wbidpf [data-testid=header]{margin-top:0}";
const _5 = "._1nc9idpf [data-testid=child]{padding-left:0}";
const _4 = "._nou7idpf [data-testid=child]{padding-bottom:0}";
const _3 = "._6ad7idpf [data-testid=child]{padding-right:0}";
const _2 = "._9a4nidpf [data-testid=child]{padding-top:0}";
const _ = "._1e0c1txw{display:flex}";
const wrapper = null;
export const Example = () => <CC>
  <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9]}</CS>
  {<div className={ax(["_1e0c1txw _9a4nidpf _6ad7idpf _nou7idpf _1nc9idpf _i6wbidpf _1fgoidpf _170zidpf _1a3lidpf"])}>
    <div data-testid="header">Header</div>
    <div data-testid="child">Body</div>
  </div>}
</CC>;