/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { padding, outline } from './external';
const _ = "._1yt46vxg{padding:5 var(--_oex9l5) 0 0}";
const styles = null;
export const Component = () => <CC>
  <CS>{[_]}</CS>
  {<div className={ax(["_1yt46vxg"])} style={{
    "--_oex9l5": ix(outline)
  }} />}
</CC>;