/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const buttonStyles = {
  primary: "_bfhk13q2 _syazu67f",
  secondary: "_bfhk17nt _syazr3uz",
  success: "_bfhkbf54 _syazu67f",
  danger: "_bfhk5scu _syazu67f"
};