/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "._syaz13q2{color:blue}";
const _ = "._syaz5scu{color:red}";
const MyComponent = () => <CC>
  <CS>{[_, _2]}</CS>
  {<div>
        <span className={ax(["_syaz5scu"])}>Red</span>
        <span className={ax(["_syaz13q2"])}>Blue</span>
      </div>}
</CC>;