/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _5 = "._1bsb1hdq{width:var(--_6f8077)}";
const _4 = "._4t3i2nrh{height:var(--_1neqek2)}";
const _3 = "._12vemgnk{background-repeat:no-repeat}";
const _2 = "._1itkh4uj{background-image:linear-gradient(to right,var(--ds-background-neutral,#0515240f) 10%,var(--ds-background-neutral-subtle,#00000000) 30%,var(--ds-background-neutral,#0515240f) 50%)}";
const _ = "._2rkofajl{border-radius:var(--ds-radius-small,3px)}";
const SkeletonRow = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2, _3, _4, _5]}</CS>
        <C {...__cmplp} style={{
      ...__cmpls,
      "--_1neqek2": ix(`${__cmplp.height}px`),
      "--_6f8077": ix(`${__cmplp.width}px`)
    }} ref={__cmplr} className={ax(["_2rkofajl _1itkh4uj _12vemgnk _4t3i2nrh _1bsb1hdq", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  SkeletonRow.displayName = 'SkeletonRow';
}
export const Component = () => <SkeletonRow height={40} width={200} />;