/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _5 = "._fhioidpf>:last-child{margin-right:0}";
const _4 = "._i12cidpf>:first-child{margin-left:0}";
const _3 = "._bmksopcn>*{margin-left:var(--space-200,4px)}";
const _2 = "._4cvr1h6o{align-items:center}";
const _ = "._1e0c1txw{display:flex}";
const styles = null;
export const Component = () => <CC>
  <CS>{[_, _2, _3, _4, _5]}</CS>
  {<div className={ax(["_1e0c1txw _4cvr1h6o _bmksopcn _i12cidpf _fhioidpf"])}>
    <span />
    <span />
    <span />
  </div>}
</CC>;