/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _3 = "._k48p8n31{font-weight:bold}";
const _2 = "._1wybdlk8{font-size:14px}";
const _ = "._syaz13q2{color:blue}";
const baseStyles = {
  color: 'blue',
  fontSize: '14px'
};
const MyComponent = () => <CC>
  <CS>{[_, _2, _3]}</CS>
  {<div className={ax(["_syaz13q2 _1wybdlk8 _k48p8n31"])}>Hello</div>}
</CC>;