/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _3 = "@keyframes k1p7rv9s{0%{transform:translateY(20px)}to{transform:translateY(0)}}";
const _2 = "@keyframes k17e8rkr{0%{opacity:0}to{opacity:1}}";
const _ = "._y44v1hgb{animation:k17e8rkr 1s ease-in,k1p7rv9s .5s ease-out}";
const fadeIn = null;
const slideUp = null;
const AnimatedDiv = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2, _3]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_y44v1hgb", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  AnimatedDiv.displayName = 'AnimatedDiv';
}