/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _5 = "._syaz13q2{color:blue}";
const _4 = "._19bv19bv{padding-left:10px}";
const _3 = "._n3td19bv{padding-bottom:10px}";
const _2 = "._u5f319bv{padding-right:10px}";
const _ = "._ca0q19bv{padding-top:10px}";
const primaryColor = 'blue';
const defaultPadding = '10px';
const StyledDiv = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2, _3, _4, _5]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_ca0q19bv _u5f319bv _n3td19bv _19bv19bv _syaz13q2", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  StyledDiv.displayName = 'StyledDiv';
}