/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _13 = "._130bglyw>div:nth-of-type(1n+4){display:none}";
const _12 = "._1bsb1osq{width:100%}";
const _11 = "._1bsb1ris{width:-moz-max-content;width:max-content}";
const _10 = "._zulp1cud{gap:4px 8px}";
const _9 = "._zulp81bl{gap:0 8px}";
const _8 = "._1e0c11p5{display:grid}";
const _7 = "._1e0c1txw{display:flex}";
const _6 = "@container cardContainer (max-width: 75px){._ek32idpf{width:0}._6xcf15vq{overflow-x:hidden}._wkiw15vq{overflow-y:hidden}._14xd15vq{visibility:hidden}}";
const _5 = "._fiawglyw:empty{display:none}";
const _4 = "._4t3i1b40{height:var(--_12p36mt)}";
const _3 = "._umaiuhbd{grid-auto-rows:var(--_13i0unl)}";
const _2 = "._yv0e1oe0{grid-template-columns:var(--_szi7k6)}";
const _ = "._4cvr1h6o{align-items:center}";
const ROW_GAP = 4;
const COLUMN_GAP = 8;
const FIELD_HEIGHT = 30;
const FIELD_HEIGHT_COMPACT = 20;
const DISPLAYING_FIELDS_MIN_CARD_WIDTH = 75;

// A reduced version of the idea-card FieldsContainer styles that produced a selector hash mismatch
// between Babel and SWC. Keep the nth-of-type selector and the container query intact.
const FieldsContainer = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    isRow,
    hasMaxContent,
    cappedFieldsDisplay,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13]}</CS>
        <C {...__cmpldp} style={{
      ...__cmpls,
      "--_szi7k6": ix(!__cmplp.isRow && '[title] fit-content(100px) [content] 1fr'),
      "--_13i0unl": ix(!__cmplp.isRow && `minmax(${FIELD_HEIGHT}px, auto)`),
      "--_12p36mt": ix(__cmplp.isRow && `${FIELD_HEIGHT_COMPACT + ROW_GAP}px`)
    }} ref={__cmplr} className={ax(["_4cvr1h6o _yv0e1oe0 _umaiuhbd _4t3i1b40 _fiawglyw _ek32idpf _6xcf15vq _wkiw15vq _14xd15vq", __cmplp.isRow ? "_1e0c1txw" : "_1e0c11p5", __cmplp.isRow ? "_zulp81bl" : "_zulp1cud", __cmplp.isRow && __cmplp.hasMaxContent ? "_1bsb1ris" : "_1bsb1osq", __cmplp.isRow && __cmplp.cappedFieldsDisplay && "_130bglyw", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  FieldsContainer.displayName = 'FieldsContainer';
}
export const Component = () => <FieldsContainer isRow hasMaxContent cappedFieldsDisplay>
    <div />
    <div />
    <div />
    <div />
  </FieldsContainer>;