[package]
name = "cssnano-postcss-normalize-unicode"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "Byte-for-byte Rust port of postcss-normalize-unicode@5.1.1."

[dependencies]
postcss-core = { workspace = true }
postcss-value-parser = { workspace = true }
browserslist-shim = { workspace = true }
cssnano-browserslist-snapshot = { workspace = true }
indexmap = { workspace = true }
