/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import React from 'react';
const _20 = "._eid31y44:before{margin-right:4px}";
const _19 = "._1kt91mp2:before{content:\"\u2022\"}";
const _18 = "._1dyz1m6u{letter-spacing:.5px}";
const _17 = "._syaz5ac6{color:#1d7afc}";
const _16 = "._1p1dangw{text-transform:uppercase}";
const _15 = "._k48pni7l{font-weight:600}";
const _14 = "._1wyb19bv{font-size:10px}";
const _13 = "._4cvr1h6o{align-items:center}";
const _12 = "._1e0c116y{display:inline-flex}";
const _11 = "._19pkftgi{margin-top:8px}";
const _10 = "._1e0c1txw{display:flex}";
const _9 = "._zulpftgi{gap:8px}";
const _8 = "._p12fnklw{max-width:20pc}";
const _7 = "._syaz15cr{color:var(--ds-text-inverse,#fff)}";
const _6 = "._bfhkcdhy{background-color:var(--ds-background-neutral-bold,#44546f)}";
const _5 = "._19bv1crf{padding-left:9pt}";
const _4 = "._n3tdftgi{padding-bottom:8px}";
const _3 = "._u5f31crf{padding-right:9pt}";
const _2 = "._ca0qftgi{padding-top:8px}";
const _ = "._2rko12b0{border-radius:var(--ds-radius-small,4px)}";
const badgeStyles = null;
const PopUpListItem = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_2rko12b0 _ca0qftgi _u5f31crf _n3tdftgi _19bv1crf _bfhkcdhy _syaz15cr _p12fnklw", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  PopUpListItem.displayName = 'PopUpListItem';
}
const PopUpList = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_9, _10, _11]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_zulpftgi _1e0c1txw _19pkftgi", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  PopUpList.displayName = 'PopUpList';
}
export const Component = ({
  services = []
}) => <div>
    <CC>
  <CS>{[_12, _13, _14, _15, _16, _17, _18, _19, _20]}</CS>
  {<span className={ax(["_1e0c116y _4cvr1h6o _1wyb19bv _k48pni7l _1p1dangw _syaz5ac6 _1dyz1m6u _1kt91mp2 _eid31y44"])}>{services.length} services</span>}
  </CC>
    <PopUpList>
      <PopUpListItem>{services.join(', ') || 'No services'}</PopUpListItem>
    </PopUpList>
  </div>;