/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { color } from './tokens';
const _ = "._syaz5scu{color:red}";
const styles = null;
export const Component = () => <CC>
  <CS>{[_]}</CS>
  {<div className={ax(["_syaz5scu"])}>Hello</div>}
</CC>;