/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "._30l35scu:hover{color:red}";
const _ = "._syaz13q2{color:blue}";
const MyComponent = () => <CC>
  <CS>{[_, _2]}</CS>
  {<div className={ax(["_syaz13q2 _30l35scu"])}>
    Hello
  </div>}
</CC>;