/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import React from 'react';
const _2 = "._19itj0fz{border:1px solid var(--ds-border,#0b120e24)}";
const _ = "._19itglyw{border:none}";
const Wrapper = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    isSummaryView,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_, _2]}</CS>
        <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax(["", __cmplp.isSummaryView ? "_19itglyw" : "_19itj0fz", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Wrapper.displayName = 'Wrapper';
}
export const Component = () => <Wrapper isSummaryView={false} />;