/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _11 = "._1bsb1ris{width:-moz-max-content;width:max-content}";
const _10 = "._1tkei63v{min-height:calc(var(--board-scroll-element-height)*1px - 8px)}";
const _9 = "._1tke1osq{min-height:100%}";
const _8 = "._yv0e16td{grid-template-columns:repeat(auto-fit,minmax(150px,1fr))}";
const _7 = "._yv0eglyw{grid-template-columns:none}";
const _6 = "._1e0c1txw{display:flex}";
const _5 = "._1e0c11p5{display:grid}";
const _4 = "._wij21bp4{grid-auto-flow:column}";
const _3 = "._i0dl1wug{flex-basis:auto}";
const _2 = "._1o9zkb7n{flex-shrink:1}";
const _ = "._16jlkb7n{flex-grow:1}";
// Mirror the sharedStyles export from board-kit.
const layout = {
  columnMargin: 6
};
const sharedStyles = {
  columnWithMarginWidth: 270 + layout.columnMargin * 2,
  zIndex: {
    boardBorders: 90
  },
  columnFixedWidth: 270,
  columnMinWidth: 150,
  columnHeaderHeight: 48
};
const fg = () => false;
export const Component = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    isFlexible,
    isSwimlaneMode,
    shouldShowSampleProjectDataNudge,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11]}</CS>
        <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax(["_16jlkb7n _1o9zkb7n _i0dl1wug _wij21bp4", __cmplp.isFlexible ? "_1e0c11p5" : "_1e0c1txw", !__cmplp.isFlexible ? "_yv0eglyw" : "_yv0e16td", __cmplp.isFlexible && !__cmplp.isSwimlaneMode && (fg('avoid_board_scroll_container_style_changes') ? "_1tke1osq" : "_1tkei63v"), __cmplp.shouldShowSampleProjectDataNudge && "_1bsb1ris", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Component.displayName = 'Component';
}
export default Component;