/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { gridSize } from './grid-size';
const _3 = "._1bahesu3{justify-content:flex-end}";
const _2 = "._1e0c1txw{display:flex}";
const _ = "._1yt419se{padding:var(--_k5d4ix) var(--_254oyp) 0 0}";
const ACTIONS_CELL_PADDING = `${gridSize / 2}px`; // dynamic via import
const styles = null;
export const Component = () => <CC>
  <CS>{[_, _2, _3]}</CS>
  {<div className={ax(["_1yt419se _1e0c1txw _1bahesu3"])} style={{
    "--_k5d4ix": ix(ACTIONS_CELL_PADDING),
    "--_254oyp": ix(TABLE_BUTTON_OUTLINE)
  }} />}
</CC>;