/* input.tsx generated by @compiled/babel-plugin v0.38.1 */
import * as React from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import Textfield from '@atlaskit/textfield';
const _2 = "._syazi7uo{color:var(--ds-text,#292a2e)}";
const _ = "._syaz1tmw{color:var(--ds-text-danger,#ae2e24)}";
const textFieldStyle = {
  invalid: "_syaz1tmw",
  valid: "_syazi7uo"
};
type Props = {
  isValid: boolean;
};
export const Example = ({
  isValid
}: Props) => <CC>
  <CS>{[_, _2]}</CS>
  {<Textfield className={ax([isValid ? textFieldStyle.valid : textFieldStyle.invalid])} />}
</CC>;