/* input.tsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import React, { createRef, useCallback, useEffect, useState, type ComponentType, type MouseEvent, type MutableRefObject, type ReactNode, type FocusEvent, useRef } from 'react';
import { type CssFunction } from '@compiled/react';
import noop from 'lodash/noop';
import type { UIAnalyticsEvent } from '@atlaskit/analytics-next';
import Heading from '@atlaskit/heading';
import { Box, Flex, xcss } from '@atlaskit/primitives';
import Spinner from '@atlaskit/spinner';
import { media } from './responsive';
import { componentWithCondition } from './component-with-condition';
import { fireUIAnalytics } from './analytics';
import { isVisualRefreshEnabled } from './feature-switch';
import { useSoftwareProjectTheming } from './software-theme';
import { Tokens } from './custom-theme-constants';
import { getIsSoftwareThemingM2Enabled } from './theming-enabled';
import { fg } from './feature-gating';
import { useModalDialogActions } from './modal-dialog-actions';
import { AnnouncerV2 } from './announcer-v2';
import { useCardOpen } from './use-card-open';
import { cardColor } from './constants.tsx';
import Expand from './expand/index.tsx';
import type { CardContainerPropsWithDragging, CardPropsWithDraggingAndStates } from './types.tsx';
import { ContextMenu } from './context-menu/index.tsx';
const _77 = "._1yt4v77o{padding:var(--ds-space-025,2px)}";
const _76 = "._syaz15fh{color:var(--_14jabjs)}";
const _75 = "._1wpz1h6o{align-self:center}";
const _74 = "._k48p1wq8{font-weight:var(--ds-font-weight-medium,500)}";
const _73 = "._slp31hna{word-wrap:break-word}";
const _72 = "._ca0qv77o{padding-top:var(--ds-space-025,2px)}";
const _71 = "._1e0c1o8l{display:inline-block}";
const _70 = "._i0dlf1ug{flex-basis:0%}";
const _69 = "._1o9zkb7n{flex-shrink:1}";
const _68 = "._16jlkb7n{flex-grow:1}";
const _67 = "._11c81psy{font:font.body}";
const _66 = "._1tke1f4h{min-height:28px}";
const _65 = "._18u0ze3t{margin-left:var(--ds-space-0,0)}";
const _64 = "._18u0x0bf{margin-left:var(--ds-space-negative-100,-8px)}";
const _63 = "._1tke1ejb{min-height:var(--ds-space-300,24px)}";
const _62 = "._4cvr1h6o{align-items:center}";
const _61 = "._bfhk1v2w{background-color:var(--_5lhzjr)}";
const _60 = "._1h6d1l7x{border-color:var(--ds-border,#0b120e24)}";
const _59 = "._irr3sgqa:hover{background-color:var(--_g5kx1x)}";
const _58 = "._10j7sgqa:focus-within{background-color:var(--_g5kx1x)}";
const _57 = "._bfhk1nnb{background-color:var(--_170mauh)}";
const _56 = "._1h6d9cd9{border-color:var(--_1tmu95r)}";
const _55 = "._1di615s3:active{background-color:var(--ds-background-selected,#e9f2fe)}";
const _54 = "._irr31rtj:hover{background-color:var(--_1smle1g)}";
const _53 = "._10j71rtj:focus-within{background-color:var(--_1smle1g)}";
const _52 = "._irr3llho:hover{background-color:var(--project-background-neutral)}";
const _51 = "._10j7llho:focus-within{background-color:var(--project-background-neutral)}";
const _50 = "._189ee4h9{border-width:var(--ds-border-width,1px)}";
const _49 = "._1dqonqa1{border-style:solid}";
const _48 = "._1h6d1j28{border-color:transparent}";
const _47 = "._30l3i7uo:hover{color:var(--ds-text,#292a2e)}";
const _46 = "._syazi7uo{color:var(--ds-text,#292a2e)}";
const _45 = "._30l31r2d:hover{color:var(--_1g6q8x)}";
const _44 = "._vp7g1r2d:focus-within{color:var(--_1g6q8x)}";
const _43 = "._irr38okp:hover{background-color:var(--_lyilio)}";
const _42 = "._10j78okp:focus-within{background-color:var(--_lyilio)}";
const _41 = "._syaz1o5v{color:var(--_fdouhv)}";
const _40 = "._bfhk1ayf{background-color:var(--_rgmfhj)}";
const _39 = "._irr315s3:hover{background-color:var(--ds-background-selected,#e9f2fe)}";
const _38 = "._bfhk15s3{background-color:var(--ds-background-selected,#e9f2fe)}";
const _37 = "._1di6hjni:active{background-color:var(--_1yuuf1b)}";
const _36 = "._1di61uj6:active{background-color:var(--_181jl6c)}";
const _35 = "._30l31lpq:hover{color:var(--_au4plk)}";
const _34 = "._vp7g1lpq:focus-within{color:var(--_au4plk)}";
const _33 = "._irr31jng:hover{background-color:var(--_xo8bol)}";
const _32 = "._10j71jng:focus-within{background-color:var(--_xo8bol)}";
const _31 = "._7ehi2ef9:focus{box-shadow:inset 0 0 0 2px var(--ds-border-focused,#4688ec)}";
const _30 = "._12y31o36{outline-width:medium}";
const _29 = "._1qu2glyw{outline-style:none}";
const _28 = "._12ji1r31{outline-color:currentColor}";
const _27 = "._18u0u2gc{margin-left:var(--ds-space-100,8px)}";
const _26 = "._2hwxu2gc{margin-right:var(--ds-space-100,8px)}";
const _25 = "._bfhk1j28{background-color:transparent}";
const _24 = "._2rko12b0{border-radius:var(--ds-radius-small,4px)}";
const _23 = "._16qst7xp{box-shadow:var(--ds-shadow-raised,0 1px 1px #1e1f2140,0 0 1px #1e1f214f)}";
const _22 = "._16qs2ef9{box-shadow:inset 0 0 0 2px var(--ds-border-focused,#4688ec)}";
const _21 = "._80om73ad{cursor:default}";
const _20 = "._80om15jw{cursor:progress}";
const _19 = "._18u01b66{margin-left:var(--ds-space-050,4px)}";
const _18 = "._otyrv77o{margin-bottom:var(--ds-space-025,2px)}";
const _17 = "._2hwx1b66{margin-right:var(--ds-space-050,4px)}";
const _16 = "._19pkv77o{margin-top:var(--ds-space-025,2px)}";
const _15 = "._syazhclr{color:var(--_1dnfcf4)}";
const _14 = "._bfhk1365{background-color:var(--_1h09nl0)}";
const _13 = "._p12f1ogy{max-width:270px}";
const _12 = "._vchhusvi{box-sizing:border-box}";
const _11 = "._2lx21bp4{flex-direction:column}";
const _10 = "._1e0c1txw{display:flex}";
const _9 = "._v56419bn{transition:background-color .14s ease-in-out,color .14s ease-in-out}";
const _8 = "._2rkofajl{border-radius:var(--ds-radius-small,3px)}";
const _7 = "._c71lidpf{max-height:0}";
const _6 = "._c71lw7q6{max-height:999px}";
const _5 = "._v5644er6{transition:max-height .3s ease-out}";
const _4 = "._18m915vq{overflow-y:hidden}";
const _3 = "._1reo15vq{overflow-x:hidden}";
const _2 = "@media (max-width:1023px){._1e051b66{padding-top:var(--ds-space-050,4px)}._1y7gu2gc{padding-right:var(--ds-space-100,8px)}._2ae21b66{padding-bottom:var(--ds-space-050,4px)}._35p0u2gc{padding-left:var(--ds-space-100,8px)}}";
const _ = "@media (min-width:1024px){._1gqru2gc{padding-top:var(--ds-space-100,8px)}._z0qsutpp{padding-right:var(--ds-space-150,9pt)}._1u24u2gc{padding-bottom:var(--ds-space-100,8px)}._14rcutpp{padding-left:var(--ds-space-150,9pt)}}";
const Container = ({
  innerRef,
  isActive = false,
  isDraggingOver = false,
  children,
  onClick = noop,
  isLoading,
  isDragging = false,
  expanded = false,
  onHoverOrFocus,
  onUnhoverOrBlur
}: CardContainerPropsWithDragging) => {
  const containerProps = {
    'data-test-id': 'software-backlog-panel.common.ui.card.container',
    'data-testid': 'software-backlog-panel.common.ui.card.container'
  };
  const {
    isSoftwareFullTheming
  } = getIsSoftwareThemingM2Enabled() ?
  // eslint-disable-next-line react-hooks/react-compiler
  // eslint-disable-next-line react-hooks/rules-of-hooks
  useSoftwareProjectTheming() : {
    isSoftwareFullTheming: false
  };
  const cardRef = createRef<HTMLDivElement>();
  useEffect(() => {
    if (cardRef && cardRef.current && cardRef.current.scrollIntoView && isLoading === true) {
      cardRef.current.scrollIntoView({
        behavior: 'smooth'
      });
    }
  }, [cardRef, isLoading]);

  // This is to prevent onUnhoverOrBlur from being triggered when focused on children
  const onBlur = useCallback((event: FocusEvent) => {
    if (innerRef?.current && !innerRef.current.contains(event.relatedTarget) && onUnhoverOrBlur) {
      onUnhoverOrBlur();
    }
  }, [innerRef, onUnhoverOrBlur]);
  return isLoading === true ? <CC>
  <CS>{[_, _2]}</CS>
  {<StaticContainer ref={cardRef} {...containerProps} className={ax(["_1gqru2gc _z0qsutpp _1u24u2gc _14rcutpp _1e051b66 _1y7gu2gc _2ae21b66 _35p0u2gc"])}>
			{children}
		</StaticContainer>}
  </CC> : <CC>
  <CS>{[_, _2]}</CS>
  {<InteractiveContainer {...containerProps} ref={innerRef} isActive={isActive} isDraggingOver={isDraggingOver} onClick={onClick} isDragging={isDragging} expanded={expanded} onMouseEnter={onHoverOrFocus} onFocus={onHoverOrFocus} onBlur={onBlur} onMouseLeave={onUnhoverOrBlur} isSoftwareFullTheming={isSoftwareFullTheming} className={ax(["_1gqru2gc _z0qsutpp _1u24u2gc _14rcutpp _1e051b66 _1y7gu2gc _2ae21b66 _35p0u2gc"])}>
			{children}
		</InteractiveContainer>}
  </CC>;
};
const Card = (props: CardPropsWithDraggingAndStates) => {
  const {
    isContentExpanded,
    toggleOpen
  } = useCardOpen(props.id);
  const {
    isSoftwareFullTheming
  } = getIsSoftwareThemingM2Enabled() ?
  // eslint-disable-next-line react-hooks/react-compiler
  // eslint-disable-next-line react-hooks/rules-of-hooks
  useSoftwareProjectTheming() : {
    isSoftwareFullTheming: false
  };
  const {
    title = '',
    subtitle = null,
    children,
    isLoading,
    isActive = false,
    itemName = '',
    itemType,
    editButton,
    id
  } = props;
  const content = typeof children === 'function' ? children(isContentExpanded) : children;
  const shouldShowContents = Boolean(content) && !isLoading;
  const [isHovered, setIsHovered] = useState(false);
  const menuTriggerRef = useRef<HTMLButtonElement>(null);
  const {
    setReturnFocusTo
  } = useModalDialogActions();
  const onToggleExpanded = (event: MouseEvent<HTMLElement>, analyticsEvent: UIAnalyticsEvent): void => {
    // stop event propagation so that the card's isActive state does not get toggled
    event.stopPropagation();
    fireUIAnalytics(analyticsEvent, 'expandToggleButton', {
      expandState: !isContentExpanded
    });
    toggleOpen();
  };
  const [announcement, setAnnouncement] = useState('');
  const showEditButton = useCallback(() => setIsHovered(true), []);
  const hideEditButton = useCallback(() => setIsHovered(false), []);
  const handleMenuOpenChange = useCallback((isOpen: boolean) => {
    if (isOpen && menuTriggerRef?.current) {
      setReturnFocusTo(menuTriggerRef);
    }
  }, [setReturnFocusTo]);
  return <Container {...props} expanded={isContentExpanded} onHoverOrFocus={showEditButton} onUnhoverOrBlur={hideEditButton}>
			<Header showChevron={shouldShowContents} visualRefresh={isVisualRefreshEnabled()}>
				{shouldShowContents && <Expand data-testid="software-backlog-panel.common.ui.card.expand" isExpanded={isContentExpanded} onToggle={onToggleExpanded} itemName={itemName} itemType={itemType} isActive={isActive} />}
				<Title data-testid="software-backlog-panel.common.ui.card.title" visualRefresh={isVisualRefreshEnabled()}>
					{isVisualRefreshEnabled() && (fg('jfp-a11y-team_fix_heading_on_backlog_card_ui') ? <Flex justifyContent="space-between" alignItems="center">
								<Box as="h3" paddingBlockStart="space.0" xcss={[titleContainerStylesNew, isActive && titleSelectedStyles, isSoftwareFullTheming && isActive && titleSelectedThemedStyles]}>
									{title}
								</Box>
								{isHovered && editButton}
							</Flex> : <Flex as="ul" justifyContent="space-between" alignItems="center" xcss={[titleContainerStyles, isActive && titleSelectedStyles, isSoftwareFullTheming && isActive && titleSelectedThemedStyles]}>
								<Box as="li" paddingBlockStart="space.0">
									{title}
								</Box>
								{isHovered && editButton}
							</Flex>)}
					{!isVisualRefreshEnabled() && <Heading as="h3" size="xsmall">
							{title}
						</Heading>}
				</Title>
				{isLoading === true && <Box xcss={cardSpinnerStyles}>
						<Spinner testId="software-backlog-panel.common.ui.card.spinner" size="small" appearance={isActive ? 'invert' : 'inherit'} />
					</Box>}
				{itemType === 'epic' && shouldShowContents && <>
						<AnnouncerV2 message={announcement} shouldAnnounce={announcement !== ''} liveMode="polite" />
						<ContextMenu cardId={id} onOpenChange={handleMenuOpenChange} triggerRef={menuTriggerRef} setAnnouncement={setAnnouncement} />
					</>}
			</Header>
			{subtitle}
			{shouldShowContents && isContentExpanded && <AnimatedHeight data-testid="software-backlog-panel.common.ui.card.content-container" aria-hidden={!isContentExpanded} isExpanded={isContentExpanded}>
					<Box xcss={contentStyles}>{content}</Box>
				</AnimatedHeight>}
		</Container>;
};
export default Card;
const cardMaxWidth = 270;
const responsiveStyles = null;

// eslint-disable-next-line @atlaskit/ui-styling-standard/no-styled -- To migrate as part of go/ui-styling-standard
const AnimatedHeight = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    isExpanded,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_3, _4, _5, _6, _7]}</CS>
        <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax(["_1reo15vq _18m915vq _v5644er6", __cmplp.isExpanded ? "_c71lw7q6" : "_c71lidpf", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  AnimatedHeight.displayName = 'AnimatedHeight';
}
const cardSpinnerStyles = xcss({
  marginLeft: 'space.150'
});
const defaultBoxShadow = "var(--ds-shadow-raised, 0px 1px 1px #1E1F2140, 0px 0px 1px #1E1F214f)";
const focusBoxShadow = `inset 0 0 0 2px ${"var(--ds-border-focused, #4688EC)"};`;
const outlineStyles = `
    outline: none;
    &:focus {
        box-shadow: ${focusBoxShadow};
    }
`;

// eslint-disable-next-line @atlaskit/ui-styling-standard/no-styled -- To migrate as part of go/ui-styling-standard
const StaticContainer = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    isLoading,
    isDraggingOver,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_8, _9, _10, _11, _12, _13, _14, _15, _16, _17, _18, _19, _20, _21, _22, _23]}</CS>
        <C {...__cmpldp} style={{
      ...__cmpls,
      "--_1h09nl0": ix(cardColor.default.mouseLeave.backgroundColor),
      "--_1dnfcf4": ix(cardColor.default.mouseLeave.textColor)
    }} ref={__cmplr} className={ax(["_2rkofajl _v56419bn _1e0c1txw _2lx21bp4 _vchhusvi _p12f1ogy _bfhk1365 _syazhclr _19pkv77o _2hwx1b66 _otyrv77o _18u01b66", __cmplp.isLoading ? "_80om15jw" : "_80om73ad", __cmplp.isDraggingOver ? "_16qs2ef9" : "_16qst7xp", __cmplp.className])} />
      </CC>;
});

// eslint-disable-next-line @atlaskit/ui-styling-standard/no-styled -- To migrate as part of go/ui-styling-standard
if (process.env.NODE_ENV !== 'production') {
  StaticContainer.displayName = 'StaticContainer';
}
const StaticContainerNew = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    isLoading,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_24, _9, _10, _11, _12, _13, _25, _15, _16, _26, _18, _27, _20, _21]}</CS>
        <C {...__cmpldp} style={{
      ...__cmpls,
      "--_1dnfcf4": ix(cardColor.default.mouseLeave.textColor)
    }} ref={__cmplr} className={ax(["_2rko12b0 _v56419bn _1e0c1txw _2lx21bp4 _vchhusvi _p12f1ogy _bfhk1j28 _syazhclr _19pkv77o _2hwxu2gc _otyrv77o _18u0u2gc", __cmplp.isLoading ? "_80om15jw" : "_80om73ad", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  StaticContainerNew.displayName = 'StaticContainerNew';
}
const InteractiveContainerOld: ComponentType<{
  ['data-test-id']: string;
  ref?: MutableRefObject<HTMLDivElement | null>;
  isDragging?: boolean;
  isActive?: boolean;
  isDraggingOver: boolean;
  tabIndex?: number;
  onClick?: (event: MouseEvent<HTMLElement>) => void;
  onMouseDown?: (event: MouseEvent<HTMLElement>) => void;
  children?: ReactNode;
  isSoftwareFullTheming?: boolean;
  css?: CssFunction | CssFunction[];
  // eslint-disable-next-line @atlaskit/ui-styling-standard/no-styled -- To migrate as part of go/ui-styling-standard
}> = forwardRef(({
  as: C = StaticContainer,
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_28, _29, _30, _31, _32, _33, _34, _35, _36, _37, _38, _39, _40, _41, _42, _43, _44, _45, _46, _47]}</CS>
        <C {...__cmplp} style={{
      ...__cmpls,
      "--_xo8bol": ix(cardColor.default.mouseOver.backgroundColor),
      "--_au4plk": ix(cardColor.default.mouseOver.textColor),
      "--_181jl6c": ix(
      // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values -- Ignored via go/DSP-18766
      cardColor.active.mouseDown.backgroundColor),
      "--_1yuuf1b": ix(
      // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values -- Ignored via go/DSP-18766
      cardColor.default.mouseDown.backgroundColor),
      "--_rgmfhj": ix(cardColor.active.mouseLeave.backgroundColor),
      "--_fdouhv": ix(cardColor.active.mouseLeave.textColor),
      "--_lyilio": ix(cardColor.active.mouseOver.backgroundColor),
      "--_1g6q8x": ix(cardColor.active.mouseOver.textColor)
    }} ref={__cmplr} className={ax(["_12ji1r31 _1qu2glyw _12y31o36 _7ehi2ef9 _10j71jng _irr31jng _vp7g1lpq _30l31lpq", __cmplp.isActive ? "_1di61uj6" : "_1di6hjni", __cmplp.isDragging && "_bfhk15s3 _irr315s3", __cmplp.isActive && "_bfhk1ayf _syaz1o5v _10j78okp _irr38okp _vp7g1r2d _30l31r2d", __cmplp.isDraggingOver && "_bfhk15s3 _irr315s3 _syazi7uo _30l3i7uo", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  InteractiveContainerOld.displayName = 'InteractiveContainerOld';
}
const InteractiveContainerNew: ComponentType<{
  ['data-test-id']: string;
  ref?: MutableRefObject<HTMLDivElement | null>;
  isDragging?: boolean;
  isActive?: boolean;
  isDraggingOver: boolean;
  tabIndex?: number;
  onClick?: (event: MouseEvent<HTMLElement>) => void;
  onMouseDown?: (event: MouseEvent<HTMLElement>) => void;
  onMouseEnter?: (event: MouseEvent<HTMLElement>) => void;
  onFocus?: (event: FocusEvent) => void;
  onBlur?: (event: FocusEvent) => void;
  onMouseLeave?: (event: MouseEvent<HTMLElement>) => void;
  children?: ReactNode;
  expanded?: boolean;
  isSoftwareFullTheming?: boolean;
  css?: CssFunction | CssFunction[];
  // eslint-disable-next-line @atlaskit/ui-styling-standard/no-styled -- To migrate as part of go/ui-styling-standard
}> = forwardRef(({
  as: C = StaticContainerNew,
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_24, _28, _29, _30, _48, _49, _50, _31, _34, _35, _51, _52, _53, _54, _55, _37, _38, _39, _56, _57, _41, _58, _59, _44, _45, _46, _47, _60, _61]}</CS>
        <C {...__cmplp} style={{
      ...__cmpls,
      "--_1smle1g": ix(
      // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values -- Ignored via go/DSP-18766
      cardColor.default.mouseOver.backgroundColor),
      "--_au4plk": ix(cardColor.default.mouseOver.textColor),
      "--_1yuuf1b": ix(
      // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values -- Ignored via go/DSP-18766
      cardColor.default.mouseDown.backgroundColor),
      "--_170mauh": ix(__cmplp.isSoftwareFullTheming ?
      // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values -- needed for theming
      Tokens.COLOR_BACKGROUND_NEUTRAL : "var(--ds-background-selected, #E9F2FE)"),
      "--_fdouhv": ix(cardColor.active.mouseLeave.textColor),
      "--_1tmu95r": ix(__cmplp.isSoftwareFullTheming ?
      // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values -- needed for theming
      Tokens.COLOR_BORDER_SELECTED : "var(--ds-border-selected, #1868DB)"),
      "--_g5kx1x": ix(__cmplp.isSoftwareFullTheming ?
      // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values -- needed for theming
      Tokens.COLOR_BACKGROUND_NEUTRAL_HOVERED :
      // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values -- Ignored via go/DSP-18766
      cardColor.active.mouseOver.backgroundColor),
      "--_1g6q8x": ix(cardColor.active.mouseOver.textColor),
      "--_5lhzjr": ix(__cmplp.isSoftwareFullTheming ?
      // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values -- needed for theming
      Tokens.WRAPPER_BACKGROUND : "var(--ds-surface, #FFFFFF)")
    }} ref={__cmplr} className={ax(["_2rko12b0 _12ji1r31 _1qu2glyw _12y31o36 _1h6d1j28 _1dqonqa1 _189ee4h9 _7ehi2ef9 _vp7g1lpq _30l31lpq", __cmplp.isSoftwareFullTheming ? "_10j7llho _irr3llho" : "_10j71rtj _irr31rtj", __cmplp.isActive ? "_1di615s3" : "_1di6hjni", __cmplp.isDragging && "_bfhk15s3 _irr315s3", __cmplp.isActive && "_2rko12b0 _1h6d9cd9 _1dqonqa1 _189ee4h9 _bfhk1nnb _syaz1o5v _10j7sgqa _irr3sgqa _vp7g1r2d _30l31r2d", __cmplp.isDraggingOver && "_bfhk15s3 _irr315s3 _syazi7uo _30l3i7uo", __cmplp.expanded && !__cmplp.isActive && "_1h6d1l7x _bfhk1v2w", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  InteractiveContainerNew.displayName = 'InteractiveContainerNew';
}
const InteractiveContainer = componentWithCondition(isVisualRefreshEnabled, InteractiveContainerNew, InteractiveContainerOld);

// eslint-disable-next-line @atlaskit/ui-styling-standard/no-styled -- To migrate as part of go/ui-styling-standard
const Header = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    showChevron,
    visualRefresh,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_8, _28, _29, _30, _10, _62, _16, _63, _31, _64, _65, _66]}</CS>
        <C {...__cmpldp} style={__cmpls} ref={__cmplr} className={ax(["_2rkofajl _12ji1r31 _1qu2glyw _12y31o36 _1e0c1txw _4cvr1h6o _19pkv77o _1tke1ejb _7ehi2ef9", __cmplp.showChevron && !__cmplp.visualRefresh ? "_18u0x0bf" : "_18u0ze3t", __cmplp.visualRefresh && "_1tke1f4h", __cmplp.className])} />
      </CC>;
});

// eslint-disable-next-line @atlaskit/ui-styling-standard/no-styled -- To migrate as part of go/ui-styling-standard
if (process.env.NODE_ENV !== 'production') {
  Header.displayName = 'Header';
}
const Title = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    visualRefresh,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_67, _68, _69, _70, _71, _72, _73, _3, _74, _75, _76, _77]}</CS>
        <C {...__cmpldp} style={{
      ...__cmpls,
      "--_14jabjs": ix(cardColor.default.textColor)
    }} ref={__cmplr} className={ax(["_11c81psy _16jlkb7n _1o9zkb7n _i0dlf1ug _1e0c1o8l _ca0qv77o _slp31hna _1reo15vq _k48p1wq8 _1wpz1h6o _syaz15fh", __cmplp.visualRefresh && "_1yt4v77o", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Title.displayName = 'Title';
}
const titleContainerStylesNew = xcss({
  font: 'font.body',
  fontWeight: "var(--ds-font-weight-medium, 500)",
  color: 'color.text.subtle',
  paddingLeft: 'space.0',
  margin: 'space.0',
  minHeight: 'space.300'
});
const titleContainerStyles = xcss({
  listStyle: 'none',
  color: 'color.text.subtle',
  paddingLeft: 'space.0',
  margin: 'space.0',
  minHeight: 'space.300'
});
const contentStyles = xcss({
  marginTop: 'space.100'
});
const titleSelectedStyles = xcss({
  color: 'color.text.selected'
});
const titleSelectedThemedStyles = xcss({
  // @ts-expect-error value does not match expected type
  // eslint-disable-next-line @atlaskit/ui-styling-standard/no-imported-style-values, @atlaskit/ui-styling-standard/no-unsafe-values -- needed for theming
  color: Tokens.COLOR_TEXT_SUBTLE
});