/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const styles = {
  small: "_ca0q1y44 _u5f31y44 _n3td1y44 _19bv1y44 _1wyb1crf",
  medium: "_ca0qftgi _u5f3ftgi _n3tdftgi _19bvftgi _1wyb7vkz",
  large: "_ca0q1crf _u5f31crf _n3td1crf _19bv1crf _1wybgktf"
};