/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _ = "._syaz1kmd{color:var(--_14m6iwb)}";
const MyComponent = ({
  isActive
}) => <CC>
  <CS>{[_]}</CS>
  {<div className={ax(["_syaz1kmd"])}>Status</div>}
</CC>;