/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _11 = "._q2twglyw>li:last-child{border-bottom:none}";
const _10 = "._1mii1dcg>li{border-bottom:1px solid #eee}";
const _9 = "._r0ehftgi>li{padding-left:8px}";
const _8 = "._75fpftgi>li{padding-bottom:8px}";
const _7 = "._18tsftgi>li{padding-right:8px}";
const _6 = "._1geeftgi>li{padding-top:8px}";
const _5 = "._19bvidpf{padding-left:0}";
const _4 = "._n3tdidpf{padding-bottom:0}";
const _3 = "._u5f3idpf{padding-right:0}";
const _2 = "._ca0qidpf{padding-top:0}";
const _ = "._qtt8glyw{list-style:none}";
const List = forwardRef(({
  as: C = "ul",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_qtt8glyw _ca0qidpf _u5f3idpf _n3tdidpf _19bvidpf _1geeftgi _18tsftgi _75fpftgi _r0ehftgi _1mii1dcg _q2twglyw", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  List.displayName = 'List';
}