/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "@keyframes k17e8rkr{0%{opacity:0}to{opacity:1}}";
const _ = "._y44v3zpo{animation:k17e8rkr 1s ease-in}";
const fadeIn = null;
const FadeInDiv = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_y44v3zpo", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  FadeInDiv.displayName = 'FadeInDiv';
}