/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import * as React from 'react';
const _3 = "._1llw1xcn:hover{transform:translateX(10px)}";
const _2 = "._t9ecz12g{transform:translateX(0)}";
const _ = "._v564gu18{transition:all .3s ease}";
const MyComponent = () => <CC>
  <CS>{[_, _2, _3]}</CS>
  {<div className={ax(["_v564gu18 _t9ecz12g _1llw1xcn"])}>
    Slide me
  </div>}
</CC>;