/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _6 = "._bfhkth1a{background-color:var(--_15e8a28)}";
const _5 = "._syaz1cj8{color:var(--_xexnhp)}";
const _4 = "._19bv19bv{padding-left:10px}";
const _3 = "._n3td19bv{padding-bottom:10px}";
const _2 = "._u5f319bv{padding-right:10px}";
const _ = "._ca0q19bv{padding-top:10px}";
const StyledBox = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    bg,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6]}</CS>
        <C {...__cmpldp} style={{
      ...__cmpls,
      "--_xexnhp": ix(__cmplp.color),
      "--_15e8a28": ix(__cmplp.bg)
    }} ref={__cmplr} className={ax(["_ca0q19bv _u5f319bv _n3td19bv _19bv19bv _syaz1cj8 _bfhkth1a", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  StyledBox.displayName = 'StyledBox';
}