/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import { cx } from '@atlaskit/css';
const _3 = "._otyru43s{margin-bottom:var(--ds-space-200,1pc)}";
const _2 = "._ca0qdbr4{padding-top:var(--ds-space-100,8px)}";
const _ = "._syaz1wbm{color:var(--ds-text-subtle,#44546f)}";
const styles = {
  base: "_syaz1wbm _ca0qdbr4",
  extra: "_otyru43s"
};
export const Component = ({
  showExtra
}) => <CC>
  <CS>{[_, _2, _3]}</CS>
  {<div xcss={cx(styles.base, showExtra ? styles.extra : null)}>content</div>}
</CC>;