/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "._k48p8n31{font-weight:bold}";
const _ = "._syaz5scu{color:red}";
const MyComponent = () => <CC>
  <CS>{[_, _2]}</CS>
  {(() => {
    const className = ax(["_syaz5scu _k48p8n31"]);
    return <div className={className}>Hello</div>;
  })()}
</CC>;