/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import React from 'react';
const _ = "._1yt482dr{padding:var(--ds-space-050,4px) var(--ds-space-150,9pt) var(--ds-space-150,9pt) var(--_5zlq23)}";
const Wrapper = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    padded,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_]}</CS>
        <C {...__cmpldp} style={{
      ...__cmpls,
      "--_5zlq23": ix(__cmplp.padded ? 'var(--ds-space-150, 12px)' : 'var(--ds-space-0, 0px)')
    }} ref={__cmplr} className={ax(["_1yt482dr", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Wrapper.displayName = 'Wrapper';
}
export const Component = () => <Wrapper padded />;