//! Byte-parity integration test for `colord::plugins::minify::minify()`.
//!
//! Vectors are generated by
//! `packages/css/scripts/colord-minify-vectors.mjs` against upstream
//! `colord@2.9.3`'s `colord(input).minify(opts)`. They are checked into
//! `tests/minify_vectors.json` — DO NOT EDIT BY HAND. Regenerate via:
//!
//!     node packages/css/scripts/colord-minify-vectors.mjs \
//!         > crates/colord/tests/minify_vectors.json
//!
//! Any divergence between this Rust port and the upstream JS surfaces
//! here. Lock-step parity is load-bearing for `postcss-colormin`'s output.

use ::colord as colord_crate;
use colord_crate::colord;
use colord_crate::plugins::minify::{minify, MinifyOpts};

const VECTORS: &str = include_str!("minify_vectors.json");

#[test]
fn rust_minify_matches_js_minify_byte_for_byte() {
    let parsed: serde_json::Value =
        serde_json::from_str(VECTORS).expect("minify_vectors.json is malformed");
    let arr = parsed.as_array().expect("vectors must be a JSON array");
    assert!(!arr.is_empty(), "no vectors loaded — regenerate minify_vectors.json");

    let mut failures: Vec<String> = Vec::new();

    for v in arr {
        let input = v["input"].as_str().expect("input string");
        let preset = v["preset"].as_str().unwrap_or("?");
        let expected = v["expected"].as_str().expect("expected string");

        // Build MinifyOpts from the JSON `opts` field. Upstream defaults
        // (when opts is null) are `{hex:true, rgb:true, hsl:true}` plus
        // `name`/`transparent`/`alphaHex` falsy — matches MinifyOpts::default().
        let opts = match v["opts"].as_object() {
            None => MinifyOpts::default(), // null -> upstream defaults
            Some(map) => {
                let g = |k: &str, dflt: bool| map.get(k).and_then(|x| x.as_bool()).unwrap_or(dflt);
                MinifyOpts {
                    // Per upstream: Object.assign({hex:!0, rgb:!0, hsl:!0}, opts)
                    // — defaults for hex/rgb/hsl are true; for the others falsy.
                    hex: g("hex", true),
                    rgb: g("rgb", true),
                    hsl: g("hsl", true),
                    name: g("name", false),
                    transparent: g("transparent", false),
                    alpha_hex: g("alphaHex", false),
                }
            }
        };

        let c = colord(input);
        if !c.is_valid() {
            failures.push(format!(
                "[{preset}] colord({input:?}) — Rust says invalid; JS produced {expected:?}"
            ));
            continue;
        }
        let actual = minify(&c, &opts);
        if actual != expected {
            failures.push(format!(
                "[{preset}] minify({input:?}, {opts:?})\n   JS={expected:?}\n   RS={actual:?}"
            ));
        }
    }

    if !failures.is_empty() {
        let n = failures.len();
        let total = arr.len();
        let summary = failures.iter().take(40).cloned().collect::<Vec<_>>().join("\n");
        let truncated = if n > 40 { format!("\n... and {} more", n - 40) } else { String::new() };
        panic!("colord minify parity violations ({n} of {total}):\n{summary}{truncated}");
    }
}
