/* input.tsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _ = "@media (min-width:30rem){._1lv75scu{color:red}}";
const media = {
  above: {
    xs: '@media (min-width: 30rem)'
  } as const
};
const styles = null;
export const Component = () => <CC>
  <CS>{[_]}</CS>
  {<div className={ax(["_1lv75scu"])}>hi</div>}
</CC>;