/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import React from 'react';
const _4 = "._1r5p1kw7._1r5p1kw7._1r5p1kw7{font-weight:inherit}";
const _3 = "._ajmmnqa1{text-decoration-style:solid}";
const _2 = "._1hms8stv{text-decoration-line:underline}";
const _ = "._4bfu1r31{text-decoration-color:currentColor}";
const BaseLink = props => <a {...props} />;
const LinkStyled = forwardRef(({
  as: C = BaseLink,
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2, _3, _4]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_4bfu1r31 _1hms8stv _ajmmnqa1 _1r5p1kw7", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  LinkStyled.displayName = 'LinkStyled';
}
export const Component = () => <LinkStyled href="#">Help link</LinkStyled>;