/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _11 = "._858u13q2:focus{border-color:blue}";
const _10 = "._1hvw1o36:focus{outline-width:medium}";
const _9 = "._49pcglyw:focus{outline-style:none}";
const _8 = "._nt751r31:focus{outline-color:currentColor}";
const _7 = "._1wybdlk8{font-size:14px}";
const _6 = "._19bv1crf{padding-left:9pt}";
const _5 = "._n3tdftgi{padding-bottom:8px}";
const _4 = "._u5f31crf{padding-right:9pt}";
const _3 = "._ca0qftgi{padding-top:8px}";
const _2 = "._2rko1y44{border-radius:4px}";
const _ = "._19it14it{border:1px solid #ccc}";
const StyledInput = forwardRef(({
  as: C = "input",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_19it14it _2rko1y44 _ca0qftgi _u5f31crf _n3tdftgi _19bv1crf _1wybdlk8 _nt751r31 _49pcglyw _1hvw1o36 _858u13q2", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  StyledInput.displayName = 'StyledInput';
}