/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _ = "._9p01fyhu{--column-header-height:48px}";
const className = null;
export const Component = () => <CC>
  <CS>{[_]}</CS>
  {<div className={ax(["_9p01fyhu"])}>custom property</div>}
</CC>;