/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _6 = "._vwz4bs82{line-height:1.5}";
const _5 = "._1wybdlk8{font-size:14px}";
const _4 = "._k48p4jg8{font-weight:normal}";
const _3 = "._1wybf6fq{font-size:18px}";
const _2 = "._k48p8n31{font-weight:bold}";
const _ = "._1wyb1tcg{font-size:24px}";
const Header = forwardRef(({
  as: C = "h1",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_1wyb1tcg _k48p8n31", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Header.displayName = 'Header';
}
const SubHeader = forwardRef(({
  as: C = "h2",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_3, _4]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_1wybf6fq _k48p4jg8", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  SubHeader.displayName = 'SubHeader';
}
const Paragraph = forwardRef(({
  as: C = "p",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_5, _6]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_1wybdlk8 _vwz4bs82", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Paragraph.displayName = 'Paragraph';
}