/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _3 = "._10wbnkob th{vertical-align:middle}";
const _2 = "._1cuj1osq th{height:100%}";
const _ = "._kqswh2mm{position:relative}";
const TableWrapper = ({
  selectedRows
}) => {
  const styles = {};
  selectedRows.forEach(index => {
    styles[`tbody tr:nth-child(${index + 1})`] = {
      backgroundColor: "var(--ds-background-selected, #E9F2FE)"
    };
  });
  return <CC>
  <CS>{[_, _2, _3]}</CS>
  {<div className={ax(["_kqswh2mm _1cuj1osq _10wbnkob"])}>
					content
				</div>}
  </CC>;
};
export const Fixture = () => <TableWrapper selectedRows={[0, 2]} />;