/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "._1nwp1yp3{-webkit-mask-image:url(example.com/mask.svg);mask-image:url(example.com/mask.svg)}";
const _ = "._1itk1an2{background-image:url(//example.com/image.png)}";
const Box = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_1itk1an2 _1nwp1yp3", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Box.displayName = 'Box';
}
export const Component = () => <Box />;