/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "._13ce1ytt >div>div:first-of-type{box-shadow:0 0 0 2px var(--ds-border-focused,#388bff) inset}";
const _ = "._1p3lidpf >div>div:first-of-type{border-width:0}";
const SELECTED_CELL_BOX_SHADOW = '0 0 0 2px var(--ds-border-focused,#388bff) inset';
export const CellContentWrapper = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_1p3lidpf _13ce1ytt", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  CellContentWrapper.displayName = 'CellContentWrapper';
}