//! Port of `packages/utils/src/hash.ts`.
//!
//! **CRITICAL**: this hash produces the class names in `atomicifyRules`.
//! Output bytes MUST be bit-identical to the JS implementation for every
//! input string — drift here renames every class in the consuming codebase.
//!
//! The upstream is `murmurhash2_gc` from
//! https://github.com/garycourt/murmurhash-js/blob/master/murmurhash2_gc.js
//!
//! ## JS-quirk fidelity
//!
//! Upstream operates on JS numbers (f64) but uses bitwise operators which
//! coerce to int32. We mirror by using i32/u32 and explicit `wrapping_*`
//! arithmetic. The tricky bit upstream is the multiplication:
//!
//! ```js
//! k = (k & 0xffff) * 0x5bd1e995 + ((((k >>> 16) * 0x5bd1e995) & 0xffff) << 16);
//! ```
//!
//! That's a workaround for JS's lack of int32 multiplication that doesn't
//! lose precision (Math.imul didn't exist when this was written). The
//! intent is `k * 0x5bd1e995` mod 2^32. We replicate the upstream
//! expression literally rather than collapsing it — the literal version is
//! what the JS engine actually computes, and we need byte parity even on
//! pathological inputs that would expose any algebraic difference.
//!
//! ## charCodeAt semantics
//!
//! `str.charCodeAt(i)` returns the UTF-16 code unit at JS index `i`. For
//! ASCII strings (the common case for class hashes) this matches byte
//! indexing. For strings containing characters above U+FFFF, JS encodes
//! them as surrogate pairs, so a 4-byte UTF-8 codepoint counts as TWO
//! UTF-16 code units. We iterate over the JS string's UTF-16 code units
//! to match exactly.

/// JS `str.charCodeAt(i) & 0xff` — index `i` is in UTF-16 code-unit space.
fn char_code_at_lo(units: &[u16], i: usize) -> u32 {
    *units.get(i).unwrap_or(&0) as u32 & 0xff
}

/// `(k & 0xffff) * 0x5bd1e995 + ((((k >>> 16) * 0x5bd1e995) & 0xffff) << 16)`.
/// Reproduces the upstream literal — equivalent to `(k * 0x5bd1e995) & 0xffffffff`.
fn mul_imul(k: u32) -> u32 {
    let lo = (k & 0xffff).wrapping_mul(0x5bd1e995);
    let hi = ((k >> 16).wrapping_mul(0x5bd1e995) & 0xffff) << 16;
    lo.wrapping_add(hi)
}

/// Port of `packages/utils/src/hash.ts`.
///
/// `seed` defaults to 0 to match the upstream `seed = 0` parameter default.
pub fn hash(input: &str) -> String {
    hash_with_seed(input, 0)
}

pub fn hash_with_seed(input: &str, seed: u32) -> String {
    // JS string length is the count of UTF-16 code units; iterate over
    // those, not Rust char/byte indices.
    let units: Vec<u16> = input.encode_utf16().collect();
    let mut l: i32 = units.len() as i32;
    let mut h: u32 = seed ^ (l as u32);
    let mut i: usize = 0;

    while l >= 4 {
        // k = c0 | (c1 << 8) | (c2 << 16) | (c3 << 24)
        let c0 = char_code_at_lo(&units, i);
        // Upstream uses `++i` inline so the indices advance during the OR.
        let c1 = char_code_at_lo(&units, i + 1);
        let c2 = char_code_at_lo(&units, i + 2);
        let c3 = char_code_at_lo(&units, i + 3);
        i += 3;
        let mut k: u32 = c0 | (c1 << 8) | (c2 << 16) | (c3 << 24);

        k = mul_imul(k);
        k ^= k >> 24;
        k = mul_imul(k);
        h = mul_imul(h) ^ k;

        l -= 4;
        i += 1;
    }

    // Tail: 3, 2, or 1 bytes; with explicit fall-through matching JS switch.
    if l == 3 {
        h ^= char_code_at_lo(&units, i + 2) << 16;
    }
    if l == 3 || l == 2 {
        h ^= char_code_at_lo(&units, i + 1) << 8;
    }
    if l == 3 || l == 2 || l == 1 {
        h ^= char_code_at_lo(&units, i);
        h = mul_imul(h);
    }

    h ^= h >> 13;
    h = mul_imul(h);
    h ^= h >> 15;

    // `(h >>> 0).toString(36)` — base-36, JS uses lowercase digits a-z.
    base36(h)
}

/// JS `Number.prototype.toString(36)` — lowercase, no padding, "0" for zero.
fn base36(mut n: u32) -> String {
    if n == 0 { return "0".to_string(); }
    const DIGITS: &[u8] = b"0123456789abcdefghijklmnopqrstuvwxyz";
    let mut buf = Vec::with_capacity(7);
    while n > 0 {
        buf.push(DIGITS[(n % 36) as usize]);
        n /= 36;
    }
    buf.reverse();
    // SAFETY: DIGITS contains only ASCII.
    unsafe { String::from_utf8_unchecked(buf) }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Test vectors generated by running the upstream JS `hash()` directly.
    /// Generated with: `node -e "console.log(require('./packages/utils/src/hash').hash('input'))"`
    /// — re-generate any time the upstream JS changes (it should not change).
    fn assert_vector(input: &str, expected: &str) {
        let actual = hash(input);
        assert_eq!(actual, expected, "hash({:?}) — expected {:?}, got {:?}", input, expected, actual);
    }

    #[test]
    fn empty_string() {
        // `hash("")` against upstream: seed=0, l=0, h=0, no loop, no tail,
        //  h ^= h>>13 = 0, h = 0*0x5bd1e995 = 0, h ^= 0>>15 = 0,
        //  (0 >>> 0).toString(36) = "0".
        assert_vector("", "0");
    }

    #[test]
    fn single_char() {
        // Smoke: any non-empty input produces non-"0".
        let h = hash("a");
        assert_ne!(h, "0");
        // Determinism.
        assert_eq!(hash("a"), h);
    }

    #[test]
    fn determinism() {
        let h1 = hash("color: red");
        let h2 = hash("color: red");
        assert_eq!(h1, h2);
    }

    #[test]
    fn distinct_inputs_distinct_outputs() {
        // A handful of nearby inputs to spot-check no obvious collisions.
        let inputs = ["color: red", "color: blue", "color:red", "color: red ", "color: red\n"];
        let outputs: Vec<_> = inputs.iter().map(|s| hash(s)).collect();
        // Same content → same hash.
        assert_eq!(hash(inputs[0]), outputs[0]);
        // Different content → different hashes (nearly always; would be a
        // collision if it weren't).
        let unique: std::collections::HashSet<_> = outputs.iter().collect();
        assert_eq!(unique.len(), inputs.len(), "expected {} distinct hashes, got {:?}", inputs.len(), outputs);
    }

    #[test]
    fn ascii_path_roundtrips() {
        // Seed-vary smoke: same input, two different seeds, distinct output.
        let a = hash_with_seed("color: red", 0);
        let b = hash_with_seed("color: red", 1);
        assert_ne!(a, b);
    }

    #[test]
    fn base36_known_values() {
        assert_eq!(base36(0), "0");
        assert_eq!(base36(1), "1");
        assert_eq!(base36(35), "z");
        assert_eq!(base36(36), "10");
        assert_eq!(base36(1295), "zz");
    }

    /// JS-locked vectors. Bytes captured by running the upstream
    /// `@compiled/utils.hash()` directly (Phase 3 §3.3 oracle at
    /// `parity-harness/hash/oracle.mjs`). Full corpus (10037 entries
    /// covering ASCII, UTF-8 multibyte, embedded NUL, surrogate pairs,
    /// >4 KiB, length-tail branches, and 10K random inputs) lives at
    /// `crates/babel-plugin/tests/hash_corpus.json` and gates via
    /// `crates/babel-plugin/tests/hash_parity.rs`. These five are an
    /// in-process smoke for fast iteration; the JSON corpus is the
    /// authoritative parity contract.
    ///
    /// To regenerate (only if upstream changes — which it must not):
    ///   bun parity-harness/hash/oracle.mjs
    #[test]
    fn known_vectors() {
        let vectors = [
            ("", "0"),
            ("a", "14mfbry"),
            ("abcd", "aougpt"),
            ("color: red", "1wszpi4"),
            ("@media (max-width: 100px)", "w2cthn"),
        ];
        for (input, expected) in vectors {
            assert_eq!(hash(input), expected, "hash({:?}) drift", input);
        }
    }
}
