/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _12 = "._1di6143u:active{background-color:navy}";
const _11 = "._irr31xek:hover{background-color:#00008b}";
const _10 = "._j5dh13gf:disabled{cursor:not-allowed}";
const _9 = "._cun917nt:disabled{background-color:gray}";
const _8 = "._80omtlke{cursor:pointer}";
const _7 = "._syazu67f{color:#fff}";
const _6 = "._bfhk13q2{background-color:blue}";
const _5 = "._19itglyw{border:none}";
const _4 = "._19bvgktf{padding-left:20px}";
const _3 = "._n3td19bv{padding-bottom:10px}";
const _2 = "._u5f3gktf{padding-right:20px}";
const _ = "._ca0q19bv{padding-top:10px}";
const Button = forwardRef(({
  as: C = "button",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_ca0q19bv _u5f3gktf _n3td19bv _19bvgktf _19itglyw _bfhk13q2 _syazu67f _80omtlke _cun917nt _j5dh13gf _irr31xek _1di6143u", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Button.displayName = 'Button';
}