/* input.tsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import React, { type FC } from 'react';
const _9 = "._kqswh2mm{position:relative}";
const _8 = "._1e0c1txw{display:flex}";
const _7 = "._1dqonqa1{border-style:solid}";
const _6 = "._1h6d1l7x{border-color:var(--ds-border,#0b120e24)}";
const _5 = "._18m915vq{overflow-y:hidden}";
const _4 = "._1reo15vq{overflow-x:hidden}";
const _3 = "._2rko1mok{border-radius:var(--ds-radius-large,8px)}";
const _2 = "._1n261q9c{flex-wrap:nowrap}";
const _ = "._2lx21bp4{flex-direction:column}";
type Props = {
  children?: React.ReactNode;
};
export const MainContainer: FC<Props> = ({
  children,
  ...props
}) => {
  return <CC>
  <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9]}</CS>
  {<div {...props} className={ax(["_2lx21bp4 _1n261q9c _2rko1mok _1reo15vq _18m915vq _1h6d1l7x _1dqonqa1 _1e0c1txw _kqswh2mm"])}>
      {children}
    </div>}
  </CC>;
};
const styles = null;