/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _4 = "._vwz4bs82{line-height:1.5}";
const _3 = "._syaz17nt{color:gray}";
const _2 = "._k48p8n31{font-weight:bold}";
const _ = "._1wyb1tcg{font-size:24px}";
const MyComponent = () => <CC>
  <CS>{[_, _2, _3, _4]}</CS>
  {<div>
        <h1 className={ax(["_1wyb1tcg _k48p8n31"])}>Title</h1>
        <p className={ax(["_syaz17nt _vwz4bs82"])}>Description</p>
      </div>}
</CC>;