/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "@keyframes k17bk4ck{0%{transform:translateX(-100%)}to{transform:translateX(0)}}";
const _ = "._y44v1bk3{animation:k17bk4ck .3s ease-in-out}";
const slideIn = null;
const Slider = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_y44v1bk3", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Slider.displayName = 'Slider';
}