/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
import * as React from 'react';
const _ = "._syaz13q2{color:blue}";
const MyComponent = ({
  className
}) => <CC>
  <CS>{[_]}</CS>
  {<div className={ax(["_syaz13q2", className])}>
    Hello
  </div>}
</CC>;