/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _5 = "._yv0e9n6h{grid-template-columns:var(--_1w2vits)}";
const _4 = "._18u0idpf{margin-left:0}";
const _3 = "._otyridpf{margin-bottom:0}";
const _2 = "._2hwxidpf{margin-right:0}";
const _ = "._19pkidpf{margin-top:0}";
const gridSize = 8;
const StatusContainer = forwardRef(({
  as: C = "div",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  const {
    widthMultiplier,
    ...__cmpldp
  } = __cmplp;
  return <CC>
        <CS>{[_, _2, _3, _4, _5]}</CS>
        <C {...__cmpldp} style={{
      ...__cmpls,
      "--_1w2vits": ix(`repeat(auto-fit,${gridSize * __cmplp.widthMultiplier}px)`)
    }} ref={__cmplr} className={ax(["_19pkidpf _2hwxidpf _otyridpf _18u0idpf _yv0e9n6h", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  StatusContainer.displayName = 'StatusContainer';
}
export const Component = ({
  widthMultiplier
}) => <StatusContainer widthMultiplier={widthMultiplier}>
    <div />
  </StatusContainer>;