/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { forwardRef } from 'react';
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _9 = "._1wyb1crf{font-size:9pt}";
const _8 = "._syazu67f{color:#fff}";
const _7 = "._bfhkbf54{background-color:green}";
const _6 = "._1e0c1o8l{display:inline-block}";
const _5 = "._2rko1crf{border-radius:9pt}";
const _4 = "._19bvftgi{padding-left:8px}";
const _3 = "._n3tdyh40{padding-bottom:2px}";
const _2 = "._u5f3ftgi{padding-right:8px}";
const _ = "._ca0qyh40{padding-top:2px}";
const Badge = forwardRef(({
  as: C = "span",
  style: __cmpls,
  ...__cmplp
}, __cmplr) => {
  if (__cmplp.innerRef) {
    throw new Error("Please use 'ref' instead of 'innerRef'.");
  }
  return <CC>
        <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9]}</CS>
        <C {...__cmplp} style={__cmpls} ref={__cmplr} className={ax(["_ca0qyh40 _u5f3ftgi _n3tdyh40 _19bvftgi _2rko1crf _1e0c1o8l _bfhkbf54 _syazu67f _1wyb1crf", __cmplp.className])} />
      </CC>;
});
if (process.env.NODE_ENV !== 'production') {
  Badge.displayName = 'Badge';
}