[package]
name = "cssnano-postcss-minify-params"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false
description = "Byte-for-byte Rust port of postcss-minify-params@5.1.4."

[dependencies]
postcss-core = { workspace = true }
postcss-value-parser = { workspace = true }
browserslist-shim = { workspace = true }
caniuse-api = { workspace = true }
cssnano-utils = { workspace = true }
