/* input.js generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _2 = "._t9ecjyd4{transform:rotate(45deg)}";
const _ = "._v5641lvb{transition:transform .3s ease}";
const MyComponent = () => <CC>
  <CS>{[_, _2]}</CS>
  {<div className={ax(["_v5641lvb _t9ecjyd4"])}>Rotated</div>}
</CC>;