/* input.jsx generated by @compiled/babel-plugin v0.38.1 */
import { ax, ix, CC, CS } from "@compiled/react/runtime";
const _12 = "._16qs1r5l{box-shadow:0 0 0 1px rgba(0,0,0,.1)}";
const _11 = "._2rko1y44{border-radius:4px}";
const _10 = "._syazd5lx{color:maroon}";
const _9 = "._bfhk188t{background-color:beige}";
const _8 = "._1wyb7vkz{font-size:1pc}";
const _7 = "._1e0c1txw{display:flex}";
const _6 = "._19it1ujt{border:1px solid #000}";
const _5 = "._19bv19bv{padding-left:10px}";
const _4 = "._n3td19bv{padding-bottom:10px}";
const _3 = "._u5f319bv{padding-right:10px}";
const _2 = "._ca0q19bv{padding-top:10px}";
const _ = "._zulp1crf{gap:9pt}";
const base = {
  fontSize: '16px',
  color: 'purple',
  padding: '8px'
};
const overrides = {
  color: 'purple',
  padding: '10px',
  border: '1px solid black'
};
const conditional = {
  color: 'teal',
  backgroundColor: 'beige'
};
export const spreadExample = null;
export const spreadTemplate = null;
export const SpreadExampleComponent = () => <CC>
  <CS>{[_, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12]}</CS>
  {<main className={ax(["_zulp1crf _ca0q19bv _u5f319bv _n3td19bv _19bv19bv _19it1ujt _1e0c1txw _1wyb7vkz _bfhk188t _syazd5lx", "_2rko1y44 _16qs1r5l"])}>
    spread styles
  </main>}
</CC>;